import { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'en' | 'fa';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
  isRTL: boolean;
}

interface LanguageProviderProps {
  children: ReactNode;
  storageKey?: string;
  defaultLanguage?: Language;
}

const translations = {
  en: {
    home: 'Home',
    about: 'About Us',
    services: 'Services',
    videoGallery: 'Video Gallery',
    magazine: 'Magazine',
    contact: 'Contact Us',
    booking: 'Book Appointment',
    hairImplant: 'Hair Implant',
    eyebrowImplant: 'Eyebrow Implant',
    eyelashImplant: 'Eyelash Implant',
    beardImplant: 'Beard Implant',
    prp: 'PRP Treatment',
    mesotherapy: 'Mesotherapy',
    heroTitle: 'Your Natural Beauty',
    heroSubtitle: 'Expert Hair & Eyebrow Implant Solutions',
    heroDescription: 'Transform your appearance with our advanced, natural-looking implant procedures. Expert care, stunning results.',
    getStarted: 'Get Started',
    learnMore: 'Learn More',
    whyChooseUs: 'Why Choose Us',
    ourServices: 'Our Services',
    testimonials: 'What Our Clients Say',
    latestNews: 'Latest from Our Magazine',
    readMore: 'Read More',
    viewAll: 'View All',
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    message: 'Message',
    send: 'Send Message',
    address: 'Address',
    followUs: 'Follow Us',
    allRights: '© 2025 Beauty Implant. All rights reserved.',
    selectService: 'Select Service',
    selectDate: 'Select Date',
    selectTime: 'Select Time',
    confirmBooking: 'Confirm Booking',
    yearsExperience: 'Years Experience',
    happyClients: 'Happy Clients',
    successRate: 'Success Rate',
    specialists: 'Specialists',
    // About page
    'about.title': 'About Us',
    'about.lead': "For over 15 years, we've been dedicated to helping our clients achieve natural, beautiful results through advanced hair and eyebrow implant procedures.",
    'about.valuesTitle': 'Our Core Values',
    'about.valuesSubtitle': 'The principles that guide everything we do',
  'about.missionTitle': 'Our Mission',
  'about.missionDefault': 'We strive to provide world-class services that restore confidence and enhance natural beauty with medical expertise and artistic vision.',
    'about.timelineTitle': 'Our Journey',
    'about.timelineSubtitle': 'A legacy of excellence and innovation',
    'about.skillsTitle': 'Our Expertise',
    'about.skillsSubtitle': 'We pride ourselves on maintaining the highest levels of proficiency across all our services, ensuring exceptional results for every client.',
    'about.teamTitle': 'Meet Our Team',
    'about.teamSubtitle': 'Our board-certified specialists are dedicated to your care',
    // Services page
    'services.subtitle': 'Comprehensive beauty solutions using advanced techniques and personalized care',
    'services.ctaTitle': 'Ready to Get Started?',
    'services.ctaBody': 'Book a free consultation to discuss your goals and create a personalized treatment plan',
    'services.ctaPrimary': 'Book a service',
    'services.ctaSecondary': 'Contact Us',
    'services.processTitle': 'Treatment Process',
    'services.faqTitle': 'Frequently Asked Questions',
    'services.noServicesSelected': 'Please select a service to view details',
  'services.other': 'Other',
    // Static service titles by slug (fallback for navigation dropdown)
    'service.hair-implant.title': 'Hair Implant',
    'service.hair-transplant.title': 'Hair Transplant',
    'service.eyebrow-implant.title': 'Eyebrow Implant',
    'service.eyelash-implant.title': 'Eyelash Implant',
    'service.beard-implant.title': 'Beard Implant',
    'service.prp.title': 'PRP Treatment',
    'service.mesotherapy.title': 'Mesotherapy',
    // Videos page
    'videos.title': 'Video Gallery',
    'videos.subtitle': 'Watch real procedures, patient testimonials, and expert guidance',
    'videos.all': 'All Videos',
    'videos.searchPlaceholder': 'Search videos...',
    'videos.noResults': 'No videos found matching your criteria',
    'videos.uncategorized': 'Uncategorized',
    'videos.playerLabel': 'Video Player',
    'videos.heroDescription': 'Locally hosted transformations imported directly from our clinic Instagram workflow.',
    'videos.heroPill': 'Handpicked in-house moments',
    'videos.heroStatVideosLabel': 'Curated videos',
    'videos.heroStatMinutesLabel': 'Minutes of storytelling',
    'videos.heroStatMinutesValue': '{{minutes}} min',
    'videos.heroStatUpdatedLabel': 'Fresh imports',
    'videos.heroStatUpdatedValue': 'Weekly',
    'videos.watch': 'Watch video',
    'videos.emptyStateTitle': 'Videos coming soon',
    'videos.emptyStateBody': 'We are curating new reels from the clinic—check back soon or follow us on Instagram for live updates.',
    'videos.typeVideo': 'Video',
    'videos.typeImage': 'Photo',
    'videos.typeCarousel': '{{count}} media',
    'videos.capturedOn': 'Captured on {{date}}',
    'videos.detailsTitle': 'Video details',
    'videos.captionLabel': 'Instagram caption',
    'videos.relatedMediaLabel': 'Gallery stills',
    'videos.sourceLink': 'View original post',
    // Magazine page
    'magazine.title': 'Beauty Magazine',
    'magazine.subtitle': 'Expert insights, tips, and the latest trends in hair and beauty care',
    'magazine.featured': 'Featured',
    'magazine.latest': 'Latest Articles',
    'magazine.loadMore': 'Load More Articles',
    'magazine.categories': 'Categories',
    'magazine.trending': 'Trending Now',
    'magazine.popularTags': 'Popular Tags',
    'magazine.general': 'General',
    'magazine.backToMagazine': 'Back to Magazine',
    'magazine.noContent': 'No content available for this article.',
    'common.share': 'Share',
    // Contact page
    'contact.subtitle': "We're here to answer your questions and help you begin your beauty journey",
    'contact.form.namePlaceholder': 'Your name',
    'contact.form.subjectPlaceholder': 'How can we help?',
    'contact.form.messagePlaceholder': 'Tell us more about your inquiry...',
    'contact.form.phoneRequired': 'Please enter your phone number',
    'contact.map.title': 'Interactive Map',
    'contact.map.addressPlaceholder': 'Your clinic address here',
    'contact.social.subtitle': 'Stay connected for beauty tips, updates, and exclusive offers',
    'contact.quickActions.title': 'Quick Actions',
    'contact.quickActions.empty': 'No quick actions configured.',
    'contact.faqs.title': 'Frequently Asked Questions',
    'contact.faqs.subtitle': 'Quick answers to common questions',
    'contact.faqs.viewAll': 'View all FAQs',
    // Booking page
    'booking.subtitle': 'Schedule your consultation or procedure in just a few simple steps',
    'booking.selectDateTimeTitle': 'Select Date & Time',
    'booking.chooseDate': 'Choose a Date',
    'booking.chooseTime': 'Choose a Time',
    'booking.noSlots': 'No available time slots for this date',
    'booking.selectDateFirst': 'Please select a date first',
    'booking.loadingTimes': 'Loading times…',
    'booking.yourInformation': 'Your Information',
    'booking.fullNamePlaceholder': 'John Doe',
    'booking.additionalNotes': 'Additional Notes',
    'booking.additionalNotesPlaceholder': 'Any special requests or information...',
    'booking.bookingSummary': 'Booking Summary',
    'booking.note': 'Note',
    'booking.confirmedTitle': 'Booking Confirmed!',
    'booking.confirmedBody': "Thank you for choosing Beauty Implant. We've sent a confirmation email with all the details of your appointment.",
    'booking.yourAppointment': 'Your Appointment',
    'booking.confirmationNumber': 'Confirmation #',
    'booking.bookAnother': 'Book Another',
    'booking.downloadReceipt': 'Download Receipt',
    'booking.back': 'Back',
    'booking.continue': 'Continue',
    // Brand & footer
    'brand.tagline': 'Your trusted partner for natural beauty enhancement',
    'footer.linksGroupDefault': 'Links',
    'brand.name': 'Beauty Implant',
    // Alts & labels
    'hero.homeAlt': 'Beauty treatment illustration',
    'about.missionHeroAlt': 'Our clinic and facilities',
    'about.missionSecondaryAlt': 'Our treatment in progress',
    'testimonials.verifiedClient': 'Verified Client',
    // Common
    'common.loading': 'Loading…',
    'about.noStats': 'No stats available',
  // Chat widget
  'chat.title': 'Chat with us',
  'chat.subtitle': "We're online",
  'chat.placeholder': 'Type your message...',
  'chat.greeting': 'Hello! How can we help you today?',
  'chat.autoReply': 'Thank you for your message! Our team will get back to you shortly.',
  'chat.open': 'Open chat',
  'chat.close': 'Close chat',
  'chat.send': 'Send',
    // Admin common
    'admin.dashboard': 'Dashboard',
    'admin.bookings': 'Bookings',
    'admin.clients': 'Clients',
    'admin.services': 'Services',
    'admin.testimonials': 'Testimonials',
    'admin.homeContent': 'Home Content',
    'admin.aboutContent': 'About Content',
    'admin.contactContent': 'Contact Content',
    'admin.seoSettings': 'SEO Settings',
    'admin.bookingConfig': 'Booking Flow Config',
    'admin.bookingInfo': 'Booking Info Cards',
  'admin.bookingInfo.addCard': 'Add Card',
  'admin.bookingInfo.reload': 'Reload',
  'admin.bookingInfo.iconLabel': 'Icon (lucide name)',
  'admin.bookingInfo.titleLabel': 'Title',
  'admin.bookingInfo.descriptionLabel': 'Description',
  'admin.bookingInfo.orderLabel': 'Order',
  'admin.bookingInfo.up': 'Up',
  'admin.bookingInfo.down': 'Down',
  'admin.bookingInfo.saved': 'Saved',
  'admin.bookingInfo.saveFailed': 'Save failed',
  'admin.bookingInfo.createFailed': 'Create failed',
  'admin.bookingInfo.deleteFailed': 'Delete failed',
  'admin.bookingInfo.orderUpdated': 'Order updated',
  'admin.bookingInfo.reorderFailed': 'Reorder failed',
    'admin.newsletter': 'Newsletter',
    'admin.translations': 'Translations',
    'admin.media': 'Media Library',
    'admin.videos': 'Videos',
    'admin.magazine': 'Magazine',
    'admin.messages': 'Messages',
    'admin.team': 'Team',
    'admin.navigation': 'Navigation',
    'admin.footerLinks': 'Footer Links',
    'admin.settings': 'Settings',
    'admin.accessControl': 'Access Control',
    'admin.logout': 'Logout',
    'admin.profileSettings': 'Profile Settings',
    'admin.preferences': 'Preferences',
    'admin.searchPlaceholder': 'Search...',
    'admin.notifications': 'Notifications',
    'admin.exitAdmin': 'Exit Admin',
    'admin.enterAdmin': 'Admin Mode',
    'admin.toggleToPublic': 'View Website',
    'admin.toggleToAdmin': 'Admin Panel',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.delete': 'Delete',
    'admin.edit': 'Edit',
    'admin.add': 'Add',
    'admin.loading': 'Loading…',
    'admin.noData': 'No data available',
    'admin.panel': 'Admin Portal',
    'admin.viewProfile': 'View Profile',
  'admin.sendEmail': 'Send Email',
  'admin.bookAppointment': 'Book Appointment',
    'admin.clientsManagement': 'Clients Management',
    'admin.clientsManagementSubtitle': 'Manage all client information and history',
    'admin.addClient': 'Add Client',
    'admin.totalClients': 'Total Clients',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.newThisMonth': 'New This Month',
    'admin.searchClientsPlaceholder': 'Search by name, email, or ID...',
    'admin.allClients': 'All Clients',
  // 'admin.export' already defined above
    'admin.client': 'Client',
    'admin.contact': 'Contact',
    'admin.joinDate': 'Join Date',
    'admin.lastVisit': 'Last Visit',
    'admin.status': 'Status',
    'admin.actions': 'Actions',
    'admin.editClient': 'Edit Client',
    'admin.fullName': 'Full name',
    'admin.email': 'Email',
    'admin.phone': 'Phone',
    'admin.notes': 'Notes',
  // duplicate removed: admin.cancel
    'admin.saveChanges': 'Save Changes',
    'admin.createClient': 'Create Client',
    'admin.inactiveDash': '—',
    'admin.nameRequired': 'Name is required',
    'admin.clientUpdated': 'Client updated',
    'admin.clientAdded': 'Client added',
    'admin.saveFailed': 'Save failed',
    'admin.deleteConfirm': 'Delete client',
    'admin.clientDeleted': 'Client deleted',
    'admin.deleteFailed': 'Delete failed',
    'admin.switchLanguage': 'Switch Language',
    'admin.dashboardOverview': 'Dashboard Overview',
    'admin.dashboardWelcome': "Welcome back! Here's what's happening today.",
  'admin.totalRevenue': 'Total Revenue',
  'admin.totalBookings': 'Total Bookings',
  'admin.activeClients': 'Active Clients',
  'admin.successRate': 'Success Rate',
    'admin.revenueOverview': 'Revenue Overview',
    'admin.servicesDistribution': 'Services Distribution',
    'admin.todaysSchedule': "Today's Schedule",
    'admin.recentBookings': 'Recent Bookings',
    'admin.viewAll': 'View All',
    'admin.quickActions': 'Quick Actions',
    'admin.newBooking': 'New Booking',
    'admin.sendMessage': 'Send Message',
    'admin.viewReports': 'View Reports',
    'admin.priceRange': 'Price Range',
    'admin.duration': 'Duration',
  'admin.durationLabel': 'Duration',
  'admin.start': 'Start',
  'admin.end': 'End',
  'admin.required': 'required',
  // 'admin.duration' already defined above
    'admin.recovery': 'Recovery',
    'admin.servicesManagement': 'Services Management',
    'admin.servicesManagementSubtitle': 'Manage all services and procedures',
    'admin.servicesContent': 'Services Content',
    'admin.servicesContentSubtitle': 'Manage services and page content',
    'admin.servicesList': 'Services List',
    'admin.servicesHero': 'Services Page Hero',
    'admin.servicesCta': 'Services Page CTA',
    'admin.ctaTitleEn': 'Title (English)',
    'admin.ctaTitleFa': 'Title (Persian)',
    'admin.ctaBodyEn': 'Body (English)',
    'admin.ctaBodyFa': 'Body (Persian)',
    'admin.ctaPrimaryEn': 'Primary Button (English)',
    'admin.ctaPrimaryFa': 'Primary Button (Persian)',
    'admin.ctaSecondaryEn': 'Secondary Button (English)',
    'admin.ctaSecondaryFa': 'Secondary Button (Persian)',
    'admin.heroTitleEn': 'Title (English)',
    'admin.heroTitleFa': 'Title (فارسی)',
    'admin.heroSubtitleEn': 'Subtitle (English)',
    'admin.heroSubtitleFa': 'Subtitle (فارسی)',
    'admin.saveHeroContent': 'Save Hero Content',
    'admin.heroContentSaved': 'Hero content saved successfully',
    'admin.heroContentSaveFailed': 'Failed to save hero content',
    'admin.addService': 'Add Service',
    'admin.totalServices': 'Total Services',
    'admin.withPriceRange': 'With Price Range',
    'admin.withDuration': 'With Duration',
    'admin.loadingServices': 'Loading services…',
    'admin.serviceUpdated': 'Service updated',
    'admin.serviceCreated': 'Service created',
    'admin.serviceDeleted': 'Service deleted',
    'admin.deleteServiceConfirm': 'Delete service',
    'admin.slugConflict': 'Slug already exists',
    'admin.requiredFieldsMissing': 'Please fill required fields: Title, Slug, Description',
    'admin.editService': 'Edit Service',
    'admin.addNewService': 'Add New Service',
    'admin.serviceNameLabel': 'Service Name*',
    'admin.subtitleLabel': 'Subtitle',
    'admin.descriptionLabel': 'Description*',
    'admin.slugLabel': 'Slug*',
    'admin.startingPriceLabel': 'Starting Price*',
    'admin.recoveryTimeLabel': 'Recovery Time*',
    'admin.imageUrlLabel': 'Image URL',
    'admin.benefitsLabel': 'Benefits',
    'admin.processStepsLabel': 'Process Steps',
    'admin.stepTitleLabel': 'Step Title',
    'admin.faqLabel': 'FAQ',
    'admin.benefitPlaceholder': 'Benefit text',
    'admin.addBenefit': 'Add Benefit',
    'admin.remove': 'Remove',
    'admin.addStep': 'Add Step',
    'admin.questionPlaceholder': 'Question*',
    'admin.answerPlaceholder': 'Answer*',
    'admin.addFaq': 'Add FAQ',
    'admin.update': 'Update',
    'admin.create': 'Create',
    'admin.bookingsManagement': 'Bookings Management',
    'admin.bookingsManagementSubtitle': 'Manage all appointments and reservations',
    'admin.newBookingAction': 'New Booking',
    'admin.searchBookingsPlaceholder': 'Search by client, ID, or service...',
    'admin.allStatus': 'All Status',
    'admin.confirmed': 'Confirmed',
    'admin.pending': 'Pending',
    'admin.cancelled': 'Cancelled',
    'admin.completed': 'Completed',
    'admin.export': 'Export',
    'admin.dateTime': 'Date & Time',
  // duplicate duration key retained earlier: using base 'admin.duration' from services stats
    'admin.price': 'Price',
    'admin.viewDetails': 'View Details',
    'admin.confirm': 'Confirm',
  // 'admin.cancel' already defined above
    'admin.close': 'Close',
    'admin.editBooking': 'Edit Booking',
    'admin.bookingDetails': 'Booking Details',
    'admin.clientName': 'Client Name',
  // 'admin.email' already defined above
  // 'admin.phone' already defined above
    'admin.service': 'Service',
    'admin.date': 'Date',
    'admin.time': 'Time',
  // 'admin.notes' already defined above
    'admin.clientRequired': 'Client and start time are required',
    'admin.bookingUpdated': 'Booking updated',
    'admin.bookingCreated': 'Booking created',
    'admin.deleteBookingConfirm': 'Delete this booking?',
    'admin.deleted': 'Deleted',
    'admin.editTestimonial': 'Edit Testimonial',
    'admin.addTestimonial': 'Add Testimonial',
    'admin.testimonialsManagement': 'Testimonials',
    'admin.testimonialsSubtitle': 'Manage patient testimonials shown on the home page',
    'admin.addTestimonialAction': 'Add Testimonial',
    'admin.name': 'Name',
    'admin.text': 'Text',
    'admin.ratingLabel': 'Rating (1-5)*',
    'admin.imageUrl': 'Image URL',
    'admin.nameTextRequired': 'Name and Text are required',
    'admin.testimonialUpdated': 'Testimonial updated',
    'admin.testimonialCreated': 'Testimonial created',
    'admin.deleteTestimonialConfirm': 'Delete testimonial from',
  // Dashboard table & chart labels
  'admin.table.id': 'ID',
  'admin.table.client': 'Client',
  'admin.table.service': 'Service',
  'admin.table.status': 'Status',
  'admin.month.jan': 'Jan',
  'admin.month.feb': 'Feb',
  'admin.month.mar': 'Mar',
  'admin.month.apr': 'Apr',
  'admin.month.may': 'May',
  'admin.month.jun': 'Jun',
  'admin.status.inProgress': 'In Progress',
  'admin.status.upcoming': 'Upcoming',
  'admin.consultation': 'Consultation',
  'admin.eyebrowDesign': 'Eyebrow Design',
    'admin.teamManagement': 'Team Management',
    'admin.teamManagementSubtitle': 'Manage team member profiles and visibility',
    'admin.newMember': 'New Member',
    'admin.totalMembers': 'Total Members',
    'admin.activeMembers': 'Active Members',
    'admin.inactiveMembers': 'Inactive',
    'admin.visibilityPercent': 'Visibility %',
    'admin.deactivate': 'Deactivate',
    'admin.activate': 'Activate',
    'admin.memberUpdated': 'Member updated',
    'admin.memberAdded': 'Member added',
    'admin.deleteMemberConfirm': 'Delete team member',
    'admin.statusUpdateFailed': 'Status update failed',
    'admin.editMember': 'Edit Member',
    'admin.newMemberDialog': 'New Member',
    'admin.role': 'Role',
    'admin.bio': 'Bio',
    'admin.activeVisible': 'Active / Visible',
    // Media Library
    'admin.mediaLibrary.title': 'Media Library',
    'admin.mediaLibrary.subtitle': 'Browse and manage uploaded images & videos',
    'admin.media.upload': 'Upload',
    'admin.media.searchPlaceholder': 'Search by alt, file name, or labels',
    'admin.media.total': 'Total',
    'admin.media.filtered': 'Filtered',
    'admin.media.noResults': 'No media items match your search.',
    'admin.media.loading': 'Loading media…',
    'admin.media.uploadDialog': 'Upload Media',
    'admin.media.altInput': 'Alt text (for images)',
    'admin.media.labelsPlaceholder': 'Labels JSON array e.g. ["hero","banner"]',
    'admin.media.uploading': 'Uploading…',
    'admin.media.uploadImage': 'Upload image',
    'admin.media.selectFileError': 'Select a file',
    'admin.media.uploaded': 'Uploaded',
    'admin.media.uploadFailed': 'Upload failed',
    'admin.media.chooseIcon': 'Choose icon',
    'admin.media.iconHelp': 'Upload an image or choose a Lucide icon',
    'admin.media.deleteConfirm': 'Delete this media item?',
    'admin.media.deleted': 'Deleted',
    'admin.media.deleteFailed': 'Delete failed',
    // Videos Management (Local Instagram import)
    'admin.videos.totalSuffix': 'videos',
    'admin.videos.importManagerTitle': 'Instagram import workflow',
    'admin.videos.importManagerSubtitle': 'Paste a reel or post URL. We’ll download the media to this server so it always loads inside Iran.',
    'admin.videos.instructionsTitle': 'How importing works',
    'admin.videos.instructionsStep1': 'Copy the Instagram link for the reel/post you want to showcase.',
    'admin.videos.instructionsStep2': 'Paste it below and choose whether it should publish now or stay in Draft.',
    'admin.videos.instructionsStep3': 'Our server downloads the media and stores it locally for fast, reliable playback.',
    'admin.videos.urlLabel': 'Instagram URL',
    'admin.videos.urlPlaceholder': 'https://www.instagram.com/reel/XXXXXXXX/',
    'admin.videos.statusLabel': 'Initial status',
    'admin.videos.importButton': 'Import video',
    'admin.videos.importing': 'Importing…',
    'admin.videos.clear': 'Clear',
    'admin.videos.urlMissing': 'Please enter an Instagram URL',
    'admin.videos.importSuccess': 'Video imported successfully',
    'admin.videos.importFailed': 'Import failed',
    'admin.videos.libraryTitle': 'Video library',
    'admin.videos.librarySubtitle': 'Manage imported Instagram media and control what appears on the public page.',
    'admin.videos.libraryEmpty': 'No videos have been imported yet.',
    'admin.videos.libraryEmptyCta': 'Use the form above to import your first reel.',
    'admin.videos.statusPublished': 'Published',
    'admin.videos.statusDraft': 'Draft',
    'admin.videos.publish': 'Publish',
    'admin.videos.unpublish': 'Unpublish',
    'admin.videos.view': 'Preview',
    'admin.videos.delete': 'Delete',
    'admin.videos.deleteConfirm': 'Delete video “{{title}}”?',
    'admin.videos.deleteSuccess': 'Video deleted',
    'admin.videos.updateSuccess': 'Video updated',
    'admin.videos.mediaCount': '{{count}} media file',
    'admin.videos.mediaCountPlural': '{{count}} media files',
    'admin.videos.sourceLink': 'Open on Instagram',
    'admin.videos.error.invalidUrl': 'Enter a valid Instagram URL.',
    'admin.videos.error.unsupportedUrl': 'Only reels, posts, and IGTV links are supported.',
    'admin.videos.error.fetchFailed': 'Instagram refused the request. Try another link or try again later.',
    'admin.videos.error.parseFailed': 'We could not parse media details from Instagram.',
    'admin.videos.error.noMedia': 'Could not find downloadable media inside that post.',
    // Messages Management
    'admin.messagesManagement.title': 'Messages & Inquiries',
    'admin.messagesManagement.subtitle': 'Manage all customer messages and contact requests',
    'admin.messages.total': 'Total Messages',
    'admin.messages.new': 'New',
    'admin.messages.replied': 'Replied',
    'admin.messages.starred': 'Starred',
    'admin.messages.inbox': 'Inbox',
    'admin.messages.selectPrompt': 'Select a message to view details',
    'admin.messages.reply': 'Reply',
    'admin.messages.archive': 'Archive',
    'admin.messages.copyToClipboard': 'Copy to clipboard',
    'admin.messages.copied': 'Copied to clipboard',
    'admin.messages.copyFailed': 'Failed to copy',
    'admin.messages.markReplied': 'Mark as Replied',
    'admin.messages.markedReplied': 'Marked as replied',
    'admin.messages.subjectPlaceholder': 'Subject',
    'admin.messages.deleteConfirm': 'Delete this message?',
    'admin.messages.deleteSuccess': 'Message deleted',
    'admin.messages.deleteFailed': 'Delete failed',
    'admin.messages.loadFailed': 'Failed to load messages',
    'admin.messages.updateFailed': 'Failed to update',
    'admin.messages.starredToast': 'Starred',
    'admin.messages.unstarredToast': 'Unstarred',
    'admin.messages.templateNote': 'This modal provides a reply template you can edit and copy into your email client. It does not send an email directly.',
    'admin.messages.template.line1': 'Hi',
    'admin.messages.template.line2': 'Thanks for reaching out to Ava Beauty Clinic. We\'ve received your message and our team will get back to you shortly.',
    'admin.messages.template.summaryHeading': 'Summary of your inquiry:',
    'admin.messages.template.line3': 'If you need immediate assistance, feel free to call us at the numbers listed on our Contact page.',
    'admin.messages.template.signature': 'Best regards,',
    'admin.messages.template.brand': 'Ava Beauty Clinic',
    // Newsletter Settings
    'admin.newsletterSettings.title': 'Newsletter Settings',
    'admin.newsletterSettings.subtitle': 'Control the newsletter block content used on the Magazine page and site footer.',
    'admin.newsletter.headlineLabel': 'Headline*',
    'admin.newsletter.descriptionLabel': 'Description',
    'admin.newsletter.buttonLabel': 'Button Label',
    'admin.newsletter.contentSection': 'Newsletter Content',
    'admin.newsletter.headlinePlaceholder': 'Stay in the loop',
    'admin.newsletter.descriptionPlaceholder': 'Get our latest articles and tips delivered to your inbox.',
    'admin.newsletter.buttonPlaceholder': 'Subscribe',
    'admin.newsletter.headlineRequired': 'Headline is required',
    'admin.newsletter.saved': 'Newsletter settings saved',
    'admin.newsletter.saveFailed': 'Save failed',
    'admin.newsletter.loadFailed': 'Failed to load newsletter',
    // SEO Settings
    'admin.seoSettings.title': 'SEO Settings',
    'admin.seoSettings.subtitle': 'Control global SEO meta fields used across the site.',
    'admin.seo.globalSection': 'Global SEO',
    'admin.seo.siteTitleLabel': 'Site Title*',
    'admin.seo.metaDescriptionLabel': 'Meta Description',
    'admin.seo.ogImageLabel': 'OpenGraph Image URL',
    'admin.seo.siteTitlePlaceholder': 'Ava Beauty Clinic',
    'admin.seo.metaDescriptionPlaceholder': 'Women’s hair & eyebrow implant clinic...',
    'admin.seo.ogImagePlaceholder': 'https://.../og.jpg',
    'admin.seo.siteTitleRequired': 'Site title is required',
    'admin.seo.saved': 'SEO settings saved',
    'admin.seo.saveFailed': 'Save failed',
    'admin.seo.loadFailed': 'Failed to load settings',

  // Admin Settings Management
  'admin.settings.title': 'Settings',
  'admin.settings.subtitle': 'Branding and email templates',
  'admin.settings.brandingTab': 'Branding',
  'admin.settings.emailsTab': 'Email Templates',
  'admin.settings.seoTab': 'Per-Page SEO',
  'admin.settings.brandingTitle': 'Branding',
  'admin.settings.logoUrl': 'Logo URL',
  'admin.settings.logoUploadButton': 'Upload logo',
  'admin.settings.logoUploadHint': 'Upload a square PNG, SVG, or JPG for best results.',
  'admin.settings.siteTitleEn': 'Brand title (English)',
  'admin.settings.siteTitleFa': 'Brand title (Persian)',
  'admin.settings.siteTitleHint': 'Displayed next to the logo in the navigation and footer.',
  'admin.settings.primaryColor': 'Primary Color',
  'admin.settings.secondaryColor': 'Secondary Color',
  'admin.settings.saveBranding': 'Save Branding',
  'admin.settings.emailsTitle': 'Email Templates',
  'admin.settings.bookingConfirmation': 'Booking Confirmation',
  'admin.settings.bookingReminder': 'Booking Reminder',
  'admin.settings.contactAutoReply': 'Contact Auto-Reply',
  'admin.settings.saveTemplates': 'Save Templates',
  'admin.settings.seoOverridesTitle': 'Per-Page SEO Overrides',
  'admin.settings.seoOverridesHint': 'Define custom title/description by path (e.g. /services, /magazine, /contact, /services/hair-implant)',
  'admin.settings.seoOverridesUsage': 'Use overrides to set localized titles and descriptions for specific routes (e.g. /services/hair-implant).',
  'admin.settings.saveSeo': 'Save SEO',
  'admin.settings.addOverride': 'Add Path Override',
  'admin.settings.path': 'Path',
  'admin.settings.titleLabel': 'Title',
  'admin.settings.titleLabelEn': 'Title (English)',
  'admin.settings.titleLabelFa': 'Title (Persian)',
  'admin.settings.descriptionLabel': 'Description',
  'admin.settings.descriptionLabelEn': 'Description (English)',
  'admin.settings.descriptionLabelFa': 'Description (Persian)',
  'admin.settings.saved': 'Settings saved',
  'admin.settings.saveFailed': 'Save failed',
  'admin.settings.loadFailed': 'Failed to load settings',

  // Admin Translations Management
  'admin.translations.title': 'Translations',
  'admin.translations.subtitle': 'Manage multi-language key/value strings used across the site',
  'admin.translations.addKey': 'Add Key',
  'admin.translations.reload': 'Reload',
  'admin.translations.totalKeys': 'Total Keys',
  'admin.translations.dirty': 'Dirty',
  'admin.translations.languages': 'Languages',
  'admin.translations.filtered': 'Filtered',
  'admin.translations.searchPlaceholder': 'Search keys or values...',
  'admin.translations.key': 'Key',
  'admin.translations.badgeNew': 'NEW',
  'admin.translations.badgeKey': 'KEY',
  'admin.translations.modified': 'Modified',
  'admin.translations.noResults': 'No translation keys match your search.',
  'admin.translations.loading': 'Loading translations…',
  'admin.translations.addDialogTitle': 'Add Translation Key',
  'admin.translations.keyPlaceholder': 'unique.key.example',
  'admin.translations.valueLabel': 'Value',
  'admin.translations.cancel': 'Cancel',
  'admin.translations.add': 'Add Key',
  'admin.translations.keyRequired': 'Key required',
  'admin.translations.keyExists': 'Key already exists',
  'admin.translations.saved': 'Translations saved',
  'admin.translations.nothingToSave': 'Nothing to save',
  'admin.reload': 'Reload',
  'admin.saving': 'Saving…',
  'admin.saveGeneric': 'Save',
  'admin.reloadGeneric': 'Reload',

  // Admin Booking Flow Config
  'admin.bookingFlow.title': 'Booking Flow Configuration',
  'admin.bookingFlow.subtitle': 'Control available time slots, blackout dates and booking disclaimers',
  'admin.bookingFlow.availableSlots': 'Available Time Slots',
  'admin.bookingFlow.availableSlotsHint': 'Comma or newline separated times in 24h format, e.g. 09:00, 10:00, 11:30',
  'admin.bookingFlow.defaultDuration': 'Default Duration (minutes)',
  'admin.bookingFlow.buffer': 'Buffer (minutes)',
  'admin.bookingFlow.blackoutDates': 'Blackout Dates',
  'admin.bookingFlow.blackoutDatesHint': 'Dates in YYYY-MM-DD comma or newline separated',
  'admin.bookingFlow.disclaimer': 'Booking Disclaimer',
  'admin.bookingFlow.saved': 'Booking configuration saved',
  'admin.bookingFlow.saveFailed': 'Save failed',
  'admin.bookingFlow.loadFailed': 'Failed to load booking configuration',
  // Home Content Management
  'admin.homeContent.title': 'Home Content Management',
  'admin.homeContent.subtitle': 'Edit hero, stats, features and CTA section',
  'admin.homeContent.heroSection': 'Hero',
  'admin.homeContent.statsSection': 'Stats',
  'admin.homeContent.addStat': 'Add Stat',
  'admin.homeContent.noStats': 'No stats defined.',
  'admin.homeContent.featuresSection': 'Features',
  'admin.homeContent.addFeature': 'Add Feature',
  'admin.homeContent.noFeatures': 'No features defined.',
  'admin.homeContent.ctaSection': 'Call To Action Block',
  'admin.homeContent.heroTitleLabel': 'Title',
  'admin.homeContent.heroSubtitleLabel': 'Subtitle',
  'admin.homeContent.heroDescriptionLabel': 'Description',
  'admin.homeContent.heroImageLabel': 'Hero Image',
  'admin.homeContent.heroImageUploadHint': 'Upload a high-quality JPG or PNG (min 1600px wide).',
  'admin.homeContent.heroImageEmpty': 'No image selected yet',
  'admin.homeContent.heroImageUpdated': 'Hero image updated',
  'admin.homeContent.heroImageRemoved': 'Hero image removed',
  'admin.homeContent.heroImageUpdateFailed': 'Failed to update hero image',
  'admin.homeContent.primaryCtaLabel': 'Primary CTA Label',
  'admin.homeContent.secondaryCtaLabel': 'Secondary CTA Label',
  'admin.homeContent.ctaHeadingLabel': 'Heading',
  'admin.homeContent.ctaSubheadingLabel': 'Subheading',
  'admin.homeContent.ctaButtonLabel': 'Button Label',
  'admin.homeContent.stat.editTitle': 'Edit Stat',
  'admin.homeContent.stat.addTitle': 'Add Stat',
  'admin.homeContent.stat.labelLabel': 'Label*',
  'admin.homeContent.stat.valueLabel': 'Value*',
  'admin.homeContent.stat.iconLabel': 'Icon',
  'admin.homeContent.feature.editTitle': 'Edit Feature',
  'admin.homeContent.feature.addTitle': 'Add Feature',
  'admin.homeContent.feature.titleLabel': 'Title*',
  'admin.homeContent.feature.descriptionLabel': 'Description',
  'admin.homeContent.feature.iconLabel': 'Icon',
  'admin.homeContent.statRequired': 'Stat label & value required',
  'admin.homeContent.statValueNumber': 'Value must be number',
  'admin.homeContent.featureTitleRequired': 'Feature title required',
  'admin.homeContent.deleteStatConfirm': 'Delete stat?',
  'admin.homeContent.deleteFeatureConfirm': 'Delete feature?',
  'admin.homeContent.saved': 'Home content saved',
  'admin.homeContent.saveFailed': 'Save failed',
  'admin.homeContent.loadFailed': 'Failed to load home content',
  // About Content Management
  'admin.aboutContent.title': 'About Content Management',
  'admin.aboutContent.subtitle': 'Edit timeline, values, skills, and mission',
  'admin.aboutContent.timelineSection': 'Timeline',
  'admin.aboutContent.addTimeline': 'Add Timeline Item',
  'admin.aboutContent.noTimeline': 'No timeline items.',
  'admin.aboutContent.valuesSection': 'Values',
  'admin.aboutContent.addValue': 'Add Value',
  'admin.aboutContent.noValues': 'No values defined.',
  'admin.aboutContent.skillsSection': 'Skills',
  'admin.aboutContent.addSkill': 'Add Skill',
  'admin.aboutContent.noSkills': 'No skills added.',
  'admin.aboutContent.missionSection': 'Mission',
  'admin.aboutContent.missionHelper': 'Short statement and supporting bullet points',
  'admin.aboutContent.missionBullets': 'Mission Bullet Points',
  'admin.aboutContent.addBullet': 'Add Bullet',
  'admin.aboutContent.noBullets': 'No bullet points yet.',
  'admin.aboutContent.timeline.editTitle': 'Edit Timeline',
  'admin.aboutContent.timeline.addTitle': 'Add Timeline',
  'admin.aboutContent.timeline.yearLabel': 'Year*',
  'admin.aboutContent.timeline.titleLabel': 'Title*',
  'admin.aboutContent.timeline.descriptionLabel': 'Description',
  'admin.aboutContent.value.editTitle': 'Edit Value',
  'admin.aboutContent.value.addTitle': 'Add Value',
  'admin.aboutContent.value.titleLabel': 'Title*',
  'admin.aboutContent.value.descriptionLabel': 'Description',
  'admin.aboutContent.value.iconLabel': 'Icon',
  'admin.aboutContent.skill.editTitle': 'Edit Skill',
  'admin.aboutContent.skill.addTitle': 'Add Skill',
  'admin.aboutContent.skill.nameLabel': 'Name*',
  'admin.aboutContent.skill.levelLabel': 'Level (0-100)*',
  'admin.aboutContent.bullet.editTitle': 'Edit Bullet',
  'admin.aboutContent.bullet.addTitle': 'Add Bullet',
  'admin.aboutContent.bullet.textLabel': 'Text*',
  'admin.aboutContent.timelineRequired': 'Year & Title required',
  'admin.aboutContent.timelineYearNumber': 'Year must be a number',
  'admin.aboutContent.valueTitleRequired': 'Value title required',
  'admin.aboutContent.skillRequired': 'Skill name & level required',
  'admin.aboutContent.skillLevelRange': 'Level must be 0-100',
  'admin.aboutContent.bulletTextRequired': 'Bullet text required',
  'admin.aboutContent.deleteTimelineConfirm': 'Delete timeline item?',
  'admin.aboutContent.deleteValueConfirm': 'Delete value?',
  'admin.aboutContent.deleteSkillConfirm': 'Delete skill?',
  'admin.aboutContent.deleteBulletConfirm': 'Delete bullet?',
  'admin.aboutContent.saved': 'About content saved',
  'admin.aboutContent.saveFailed': 'Save failed',
  'admin.aboutContent.loadFailed': 'Failed to load About content',
  // Contact Content Management
  'admin.contactContent.title': 'Contact Content Management',
  'admin.contactContent.subtitle': 'Edit contact info blocks, FAQs, social links, quick actions',
  'admin.contactContent.blocksSection': 'Info Blocks',
  'admin.contactContent.addBlock': 'Add Block',
  'admin.contactContent.noBlocks': 'No info blocks defined.',
  'admin.contactContent.faqSection': 'FAQ',
  'admin.contactContent.addFaq': 'Add FAQ',
  'admin.contactContent.noFaq': 'No FAQ items.',
  'admin.contactContent.socialSection': 'Social Links',
  'admin.contactContent.addSocial': 'Add Link',
  'admin.contactContent.noSocial': 'No social links.',
  'admin.contactContent.quickSection': 'Quick Actions',
  'admin.contactContent.addQuick': 'Add Action',
  'admin.contactContent.noQuick': 'No quick actions.',
  'admin.contactContent.mapSection': 'Map & Location',
  'admin.contactContent.mapHint': 'Paste coordinates from Google Maps',
  'admin.contactContent.map.latitude': 'Latitude',
  'admin.contactContent.map.longitude': 'Longitude',
  'admin.contactContent.map.zoom': 'Zoom',
  'admin.contactContent.map.markerLabel': 'Marker Label',
  'admin.contactContent.map.placeholder': 'Enter coordinates to preview the live map.',
  'admin.contactContent.block.editTitle': 'Edit Block',
  'admin.contactContent.block.addTitle': 'Add Block',
  'admin.contactContent.block.typeLabel': 'Type*',
  'admin.contactContent.block.titleLabel': 'Title*',
  'admin.contactContent.block.valuesLabel': 'Values*',
  'admin.contactContent.block.addValue': 'Add Value',
  'admin.contactContent.faq.editTitle': 'Edit FAQ',
  'admin.contactContent.faq.addTitle': 'Add FAQ',
  'admin.contactContent.faq.questionLabel': 'Question*',
  'admin.contactContent.faq.answerLabel': 'Answer*',
  'admin.contactContent.social.editTitle': 'Edit Social Link',
  'admin.contactContent.social.addTitle': 'Add Social Link',
  'admin.contactContent.social.platformLabel': 'Platform*',
  'admin.contactContent.social.iconLabel': 'Icon',
  'admin.contactContent.social.chooseIcon': 'Choose Icon',
  'admin.contactContent.social.iconHint': 'Upload an image or pick a Lucide icon',
  'admin.contactContent.social.iconSourceLucide': 'Lucide Icon',
  'admin.contactContent.social.iconSourceUpload': 'Image Upload',
  'admin.contactContent.social.iconSourceNone': 'Default',
  'admin.contactContent.social.urlLabel': 'URL*',
  'admin.contactContent.quick.editTitle': 'Edit Quick Action',
  'admin.contactContent.quick.addTitle': 'Add Quick Action',
  'admin.contactContent.quick.labelLabel': 'Label*',
  'admin.contactContent.quick.typeLabel': 'Type*',
  'admin.contactContent.quick.targetLabel': 'Target*',
  'admin.contactContent.blockTitleRequired': 'Block title required',
  'admin.contactContent.blockValueRequired': 'At least one value required',
  'admin.contactContent.faqRequired': 'Question and answer required',
  'admin.contactContent.socialRequired': 'Platform and URL required',
  'admin.contactContent.quickRequired': 'Label and target required',
  'admin.contactContent.deleteBlockConfirm': 'Delete block?',
  'admin.contactContent.deleteFaqConfirm': 'Delete FAQ?',
  'admin.contactContent.deleteSocialConfirm': 'Delete social link?',
  'admin.contactContent.deleteQuickConfirm': 'Delete quick action?',
  'admin.contactContent.saved': 'Contact content saved',
  'admin.contactContent.saveFailed': 'Save failed',
  'admin.contactContent.loadFailed': 'Failed to load contact content',
  // Navigation Management
  'admin.navigationManagement.title': 'Navigation',
  'admin.navigationManagement.addItem': 'Add Item',
  'admin.navigationManagement.saving': 'Saving…',
  'admin.navigationManagement.save': 'Save',
  'admin.navigationManagement.saved': 'Navigation saved',
  'admin.navigationManagement.loadFailed': 'Failed to load navigation',
  'admin.navigationManagement.saveFailed': 'Save failed',
  'admin.navigationManagement.label': 'Label',
  'admin.navigationManagement.path': 'Path',
  'admin.navigationManagement.visible': 'Visible',
  // Footer Links Management
  'admin.footerLinksManagement.title': 'Footer Links',
  'admin.footerLinksManagement.addLink': 'Add Link',
  'admin.footerLinksManagement.saving': 'Saving…',
  'admin.footerLinksManagement.save': 'Save',
  'admin.footerLinksManagement.saved': 'Footer links saved',
  'admin.footerLinksManagement.loadFailed': 'Failed to load footer links',
  'admin.footerLinksManagement.saveFailed': 'Save failed',
  'admin.footerLinksManagement.label': 'Label',
  'admin.footerLinksManagement.url': 'URL',
  'admin.footerLinksManagement.group': 'Group',
    // Common additions
    'common.back': 'Back',
    'common.continue': 'Continue',
    'common.error': 'Error',
    'common.failedToLoad': 'Failed to load',
    'common.emDash': '—',
    'common.justNow': 'Just now',
    // Home additions
    'home.loadFailed': 'Failed to load home content',
    // Services public additions
    'services.loadFailed': 'Failed to load services',
    'services.loading': 'Loading services…',
    'services.tabBenefits': 'Benefits',
    'services.tabProcess': 'Process',
    'services.tabFaq': 'FAQ',
    'services.benefitsSuffix': 'Benefits',
    'services.price': 'Price',
    'services.duration': 'Duration',
    'services.recovery': 'Recovery',
    // Booking public additions
    'booking.selectServiceError': 'Please select service, date and time',
    'booking.submitSuccess': 'Booking submitted! We will confirm shortly.',
    'booking.submitFailed': 'Booking failed',
    'booking.summary.service': 'Service:',
    'booking.summary.date': 'Date:',
    'booking.summary.time': 'Time:',
    'booking.summary.duration': 'Duration:',
    'booking.summary.price': 'Price:',
    // Contact public additions
    'contact.loadFailed': 'Failed to load contact data',
    'contact.loading': 'Loading…',
    'contact.form.subjectLabel': 'Subject',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.phonePlaceholder': '+1 (555) 000-0000',
    'contact.form.sending': 'Sending…',
    'contact.form.sentSuccess': "Message sent successfully! We'll get back to you soon.",
    'contact.form.sentFailed': 'Failed to send message',
    'contact.faqs.moreQuestionsIntro': 'Have more questions?',
    // Magazine public additions
    'magazine.loadFailed': 'Failed to load magazine data',
    'magazine.loading': 'Loading…',
    'magazine.minReadSuffix': 'min read',
    'magazine.newsletter.defaultHeadline': 'Subscribe to Newsletter',
    'magazine.newsletter.defaultDescription': 'Get the latest beauty tips and exclusive offers directly to your inbox',
    'magazine.newsletter.defaultButton': 'Subscribe Now',
    // Videos public additions
    'videos.loadFailed': 'Failed to load videos',
    'videos.loading': 'Loading videos…',
    'videos.viewsSuffix': 'views',
    'videos.playerPlaceholder': 'Video Player',
    'videos.instagram.statusHeading': 'Instagram sync status',
    'videos.instagram.connected': 'Connected',
    'videos.instagram.disconnected': 'Disconnected',
    'videos.instagram.profile': 'Profile',
    'videos.instagram.notConnected': 'Not connected',
    'videos.instagram.lastSynced': 'Last synced',
    'videos.instagram.tokenExpiry': 'Access expiry',
    'videos.instagram.expiresInDays': 'Expires in {{days}} days',
    'videos.instagram.feedSource': 'Feed source',
    'videos.instagram.feedSourceUnknown': 'Unknown',
    'videos.instagram.refreshFeed': 'Refresh feed',
    'videos.instagram.openProfile': 'Open Instagram profile',
    'videos.instagram.aboutTitle': 'How this works',
    'videos.instagram.aboutBody': 'Videos on this page come straight from your official Instagram account so visitors always see your latest transformations.',
    'videos.instagram.aboutItem1': 'Securely authenticate once from the admin dashboard.',
    'videos.instagram.aboutItem2': 'We sync highlights automatically and cache them for fast page loads.',
    'videos.instagram.aboutItem3': 'New posts appear here shortly after Instagram publishes them.',
    'videos.instagram.adminHint': 'Need to switch accounts? Visit the admin portal → Content → Videos.',
    'videos.instagram.loginRequired': 'Please connect your Instagram business account from the admin dashboard to showcase your latest reels and videos here.',
    'videos.instagram.goToAdmin': 'Open admin dashboard',
    'videos.instagram.viewPost': 'View on Instagram',
    'videos.instagram.typeVideo': 'Video',
    'videos.instagram.typeImage': 'Image',
    'videos.instagram.minutesAgo': '{{minutes}}m ago',
    'videos.instagram.hoursAgo': '{{hours}}h ago',
    'videos.instagram.daysAgo': '{{days}}d ago',
    // Admin Magazine Management
    'admin.magazine.totalSuffix': 'articles total',
    'admin.magazine.newArticle': 'New Article',
    'admin.magazine.editArticle': 'Edit Article',
    'admin.magazine.titleRequired': 'Title & Slug required',
    'admin.magazine.updated': 'Article updated',
    'admin.magazine.created': 'Article created',
    'admin.magazine.slugConflict': 'Slug already exists',
    'admin.magazine.saveFailed': 'Save failed',
    'admin.magazine.loadFailed': 'Failed to load content',
    'admin.magazine.featureToggleFailed': 'Feature toggle failed',
    'admin.magazine.deleteConfirm': 'Delete article',
    'admin.magazine.deleteFailed': 'Delete failed',
    'admin.magazine.featured': 'Featured',
    'admin.magazine.unfeature': 'Unfeature',
    'admin.magazine.feature': 'Feature',
    'admin.magazine.slugLabel': 'Slug*',
    'admin.magazine.titleLabel': 'Title*',
    'admin.magazine.excerptLabel': 'Excerpt',
    'admin.magazine.imageUrlLabel': 'Image URL',
    'admin.magazine.readTimeLabel': 'Read Time (min)',
    'admin.magazine.statusLabel': 'Status',
    'admin.magazine.featuredLabel': 'Featured',
    'admin.magazine.categoryLabel': 'Category',
    'admin.magazine.tagsLabel': 'Tags',
    'admin.magazine.noTags': 'No tags',
    'admin.magazine.update': 'Update',
    'admin.magazine.create': 'Create',
    // Admin Users Management
    'admin.adminUsers.title': 'Access Control',
    'admin.adminUsers.subtitle': 'Manage admin users & roles',
    'admin.adminUsers.addUser': 'Add Admin User',
    'admin.adminUsers.total': 'Total',
    'admin.adminUsers.active': 'Active',
    'admin.adminUsers.inactive': 'Inactive',
    'admin.adminUsers.superadmins': 'Superadmins',
    'admin.adminUsers.searchPlaceholder': 'Search email, name, role...',
    'admin.adminUsers.allRoles': 'All Roles',
    'admin.adminUsers.superadminPlural': 'Superadmins',
    'admin.adminUsers.adminPlural': 'Admins',
    'admin.adminUsers.editorPlural': 'Editors',
    'admin.adminUsers.viewerPlural': 'Viewers',
    'admin.adminUsers.emailOptional': 'Email (optional if username set)',
    'admin.adminUsers.usernameOptional': 'Username (optional if email set)',
    'admin.adminUsers.usernameLabel': 'Username',
    'admin.adminUsers.nameLabel': 'Name',
    'admin.adminUsers.roleLabel': 'Role',
    'admin.adminUsers.statusLabel': 'Status',
    'admin.adminUsers.initialPassword': 'Initial Password',
    'admin.adminUsers.resetPasswordOptional': 'Reset Password (optional)',
    'admin.adminUsers.deactivate': 'Deactivate',
    'admin.adminUsers.activate': 'Activate',
    'admin.adminUsers.viewDetails': 'View Details',
    'admin.adminUsers.edit': 'Edit',
    'admin.adminUsers.delete': 'Delete',
    'admin.adminUsers.detailsTitle': 'Admin User Details',
    'admin.adminUsers.editTitle': 'Edit Admin User',
    'admin.adminUsers.addTitle': 'Add Admin User',
    'admin.adminUsers.emailOrUsernameRequired': 'Email or username required',
    'admin.adminUsers.passwordRequired': 'Password required',
    'admin.adminUsers.updated': 'Admin user updated',
    'admin.adminUsers.created': 'Admin user created',
    'admin.adminUsers.emailExists': 'Email already exists',
    'admin.adminUsers.saveFailed': 'Save failed',
    'admin.adminUsers.deleteConfirm': 'Delete admin user',
    'admin.adminUsers.deleteFailed': 'Delete failed',
    'admin.adminUsers.deleted': 'Admin user deleted',
    'admin.adminUsers.saveChanges': 'Save Changes',
    'admin.adminUsers.createUser': 'Create User',
    // Messages Management remaining literals mapping
    'admin.messages.replyButton': 'Reply',
    'admin.messages.archiveButton': 'Archive',
    'admin.messages.replyTo': 'Reply to',
    'admin.messages.subjectLabel': 'Subject',
    'admin.messages.copyToClipboardButton': 'Copy to clipboard',
    'admin.messages.markRepliedButton': 'Mark as Replied',
  // duplicated older toast keys replaced by unified starred/unstarredToast already present; remove duplicates
    'admin.videos.reorder': 'Reorder',
    'admin.videos.reorderTitle': 'Reorder Videos',
    'admin.videos.reorderDesc': 'Drag and drop to reorder videos',
    'admin.videos.reorderSuccess': 'Order saved successfully',
    'admin.videos.reorderFailed': 'Failed to save order',
    'admin.settings.notificationsTab': 'Notifications',
    'admin.settings.notificationsTitle': 'Notifications',
    'admin.settings.telegramBotToken': 'Telegram Bot Token',
    'admin.settings.telegramBotTokenHint': 'Get it from @BotFather',
    'admin.settings.telegramChatId': 'Chat ID',
    'admin.settings.telegramChatIdHint': 'Send /start to your bot to get this ID',
    'admin.settings.saveNotifications': 'Save Notifications',
  },
  fa: {
    'admin.videos.reorder': 'تغییر ترتیب',
    'admin.videos.reorderTitle': 'تغییر ترتیب ویدیوها',
    'admin.videos.reorderDesc': 'برای تغییر ترتیب، ویدیوها را بکشید و رها کنید',
    'admin.videos.reorderSuccess': 'ترتیب با موفقیت ذخیره شد',
    'admin.videos.reorderFailed': 'ذخیره ترتیب ناموفق بود',
    'admin.videos.importManagerTitle': 'مدیریت وارد کردن',
    'admin.videos.importManagerSubtitle': 'وارد کردن ویدیو از اینستاگرام',
    'admin.videos.libraryTitle': 'کتابخانه',
    'admin.videos.librarySubtitle': 'کتابخانه ویدیو',
    'admin.videos.statusPublished': 'منتشر شده',
    'admin.videos.statusDraft': 'پیش‌نویس',
    'admin.videos.mediaCount': '{{count}} رسانه',
    'admin.videos.mediaCountPlural': '{{count}} رسانه',
    'admin.videos.sourceLink': 'منبع',
    'admin.videos.view': 'مشاهده',
    'admin.videos.unpublish': 'لغو انتشار',
    'admin.videos.publish': 'انتشار',
    'admin.videos.delete': 'حذف',
    'admin.videos.instructionsTitle': 'راهنما',
    'admin.videos.instructionsStep1': 'لینک پست اینستاگرام را کپی کنید',
    'admin.videos.instructionsStep2': 'لینک را در کادر بالا وارد کنید',
    'admin.videos.instructionsStep3': 'برای دانلود و افزودن به کتابخانه، روی "وارد کردن" کلیک کنید',
    'admin.videos.importButton': 'وارد کردن',
    'admin.videos.error.invalidUrl': 'آدرس نامعتبر است',
    'admin.videos.error.unsupportedUrl': 'آدرس پشتیبانی نمی‌شود',
    'admin.videos.error.fetchFailed': 'دریافت اطلاعات ناموفق بود',
    'admin.videos.error.parseFailed': 'پردازش اطلاعات ناموفق بود',
    'admin.videos.error.noMedia': 'رسانه‌ای یافت نشد',
    'admin.videos.importFailed': 'وارد کردن ناموفق بود',
    'admin.clear': 'پاک کردن',
    'admin.reload': 'بارگذاری مجدد',
    'admin.cancel': 'لغو',
    'admin.save': 'ذخیره',
    home: 'خانه',
    about: 'درباره ما',
    services: 'خدمات',
    videoGallery: 'گالری ویدیو',
    magazine: 'مجله',
    contact: 'تماس با ما',
    booking: 'رزرو نوبت',
    hairImplant: 'کاشت موی سر',
    eyebrowImplant: 'کاشت ابرو',
    eyelashImplant: 'کاشت مژه',
    beardImplant: 'کاشت ریش',
    prp: 'درمان PRP',
    mesotherapy: 'مزوتراپی',
    heroTitle: 'زیبایی طبیعی شما',
    heroSubtitle: 'راهکارهای تخصصی کاشت مو و ابرو',
    heroDescription: 'ظاهر خود را با روش‌های پیشرفته و طبیعی ما متحول کنید. مراقبت تخصصی، نتایج شگفت‌انگیز.',
    getStarted: 'شروع کنید',
    learnMore: 'بیشتر بدانید',
    whyChooseUs: 'چرا ما را انتخاب کنید',
    ourServices: 'خدمات ما',
    testimonials: 'نظرات مشتریان',
    latestNews: 'آخرین مطالب مجله',
    readMore: 'ادامه مطلب',
    viewAll: 'مشاهده همه',
    name: 'نام',
    email: 'ایمیل',
    phone: 'تلفن',
    message: 'پیام',
    send: 'ارسال پیام',
    address: 'آدرس',
    followUs: 'ما را دنبال کنید',
    allRights: '© ۲۰۲۵ کاشت زیبایی. تمامی حقوق محفوظ است.',
    selectService: 'انتخاب خدمت',
    selectDate: 'انتخاب تاریخ',
    selectTime: 'انتخاب زمان',
    confirmBooking: 'تایید رزرو',
    yearsExperience: 'سال تجربه',
    happyClients: 'مشتری راضی',
    successRate: 'نرخ موفقیت',
    specialists: 'متخصص',
    // About page
    'about.title': 'درباره ما',
    'about.lead': 'بیش از ۱۵ سال است که با استفاده از روش‌های پیشرفته، به مراجعین کمک می‌کنیم تا به نتایج طبیعی و زیبا دست یابند.',
    'about.valuesTitle': 'ارزش‌های ما',
    'about.valuesSubtitle': 'اصولی که راهنمای کار ما هستند',
  'about.missionTitle': 'ماموریت ما',
  'about.missionDefault': 'می‌کوشیم با تکیه بر دانش پزشکی و نگاه هنری، خدماتی در سطح جهانی ارائه کنیم تا اعتمادبه‌نفس را بازگردانیم و زیبایی طبیعی را تقویت کنیم.',
    'about.timelineTitle': 'سفر ما',
    'about.timelineSubtitle': 'میراثی از برتری و نوآوری',
    'about.skillsTitle': 'تخصص ما',
    'about.skillsSubtitle': 'در بالاترین سطح مهارت در تمام خدمات خود می‌بالیم تا بهترین نتایج را ارائه دهیم.',
    'about.teamTitle': 'تیم ما را بشناسید',
    'about.teamSubtitle': 'متخصصان ما با گواهینامه‌های معتبر در کنار شما هستند',
    // Services page
    'services.subtitle': 'راه‌حل‌های جامع زیبایی با تکنیک‌های پیشرفته و مراقبت شخصی‌سازی‌شده',
    'services.ctaTitle': 'آماده شروع هستید؟',
    'services.ctaBody': 'برای مشاوره رایگان و برنامه‌ریزی درمان اختصاصی، وقت رزرو کنید',
    'services.ctaPrimary': 'رزرو نوبت',
    'services.ctaSecondary': 'تماس با ما',
    'services.processTitle': 'فرآیند درمان',
    'services.faqTitle': 'سؤالات پرتکرار',
    'services.noServicesSelected': 'لطفاً برای مشاهده جزئیات، یک سرویس انتخاب کنید',
  'services.other': 'سایر',
    // Static service titles by slug (fallback for navigation dropdown)
    'service.hair-implant.title': 'کاشت موی سر',
    'service.hair-transplant.title': 'کاشت مو',
    'service.eyebrow-implant.title': 'کاشت ابرو',
    'service.eyelash-implant.title': 'کاشت مژه',
    'service.beard-implant.title': 'کاشت ریش',
    'service.prp.title': 'درمان PRP',
    'service.mesotherapy.title': 'مزوتراپی',
    
    
  // Admin Settings Management
  'admin.settings.title': 'تنظیمات',
  'admin.settings.subtitle': 'برندسازی و الگوهای ایمیل',
  'admin.settings.brandingTab': 'برندسازی',
  'admin.settings.emailsTab': 'الگوهای ایمیل',
  'admin.settings.seoTab': 'سئوی هر صفحه',
  'admin.settings.brandingTitle': 'برندسازی',
  'admin.settings.logoUrl': 'آدرس لوگو',
  'admin.settings.logoUploadButton': 'آپلود لوگو',
  'admin.settings.logoUploadHint': 'برای بهترین نتیجه لوگوی مربعی با فرمت PNG، SVG یا JPG آپلود کنید.',
  'admin.settings.siteTitleEn': 'عنوان برند (انگلیسی)',
  'admin.settings.siteTitleFa': 'عنوان برند (فارسی)',
  'admin.settings.siteTitleHint': 'کنار لوگو در ناوبری و فوتر نمایش داده می‌شود.',
  'admin.settings.primaryColor': 'رنگ اصلی',
  'admin.settings.secondaryColor': 'رنگ ثانویه',
  'admin.settings.saveBranding': 'ذخیره برندسازی',
  'admin.settings.emailsTitle': 'الگوهای ایمیل',
  'admin.settings.bookingConfirmation': 'تایید رزرو',
  'admin.settings.bookingReminder': 'یادآوری رزرو',
  'admin.settings.contactAutoReply': 'پاسخ خودکار تماس',
  'admin.settings.saveTemplates': 'ذخیره الگوها',
  'admin.settings.seoOverridesTitle': 'بازنویسی سئوی هر صفحه',
  'admin.settings.seoOverridesHint': 'عنوان/توضیحات سفارشی بر اساس مسیر تعریف کنید (مثلا /services، /magazine، /contact، /services/hair-implant)',
  'admin.settings.seoOverridesUsage': 'برای هر مسیر (مانند /services/hair-implant) عنوان و توضیحات محلی‌سازی شده تعریف کنید.',
  'admin.settings.saveSeo': 'ذخیره سئو',
  'admin.settings.addOverride': 'افزودن مسیر جدید',
  'admin.settings.path': 'مسیر',
  'admin.settings.titleLabel': 'عنوان',
  'admin.settings.titleLabelEn': 'عنوان (انگلیسی)',
  'admin.settings.titleLabelFa': 'عنوان (فارسی)',
  'admin.settings.descriptionLabel': 'توضیحات',
  'admin.settings.descriptionLabelEn': 'توضیحات (انگلیسی)',
  'admin.settings.descriptionLabelFa': 'توضیحات (فارسی)',
  'admin.settings.saved': 'تنظیمات ذخیره شد',
  'admin.settings.saveFailed': 'ذخیره ناموفق بود',
  'admin.settings.loadFailed': 'بارگذاری تنظیمات ناموفق بود',
  'admin.settings.notificationsTab': 'اعلان‌ها',
  'admin.settings.notificationsTitle': 'تنظیمات اعلان‌ها',
  'admin.settings.telegramBotToken': 'توکن ربات تلگرام',
  'admin.settings.telegramBotTokenHint': 'از @BotFather دریافت کنید',
  'admin.settings.telegramChatId': 'شناسه چت (Chat ID)',
  'admin.settings.telegramChatIdHint': 'برای دریافت شناسه، دستور /start را به ربات بفرستید',
  'admin.settings.saveNotifications': 'ذخیره اعلان‌ها',
    
  // Admin Translations Management
  'admin.translations.title': 'ترجمه‌ها',
  'admin.translations.subtitle': 'مدیریت کلید/مقدار چندزبانه مورد استفاده در سراسر سایت',
  'admin.translations.addKey': 'افزودن کلید',
  'admin.translations.reload': 'بارگذاری مجدد',
  'admin.translations.totalKeys': 'کل کلیدها',
  'admin.translations.dirty': 'تغییریافته',
  'admin.translations.languages': 'زبان‌ها',
  'admin.translations.filtered': 'فیلتر شده',
  'admin.translations.searchPlaceholder': 'جستجوی کلید یا مقدار...',
  'admin.translations.key': 'کلید',
  'admin.translations.badgeNew': 'جدید',
  'admin.translations.badgeKey': 'کلید',
  'admin.translations.modified': 'تغییر کرده',
  'admin.translations.noResults': 'هیچ کلیدی با جستجوی شما یافت نشد.',
  'admin.translations.loading': 'در حال بارگذاری ترجمه‌ها…',
  'admin.translations.addDialogTitle': 'افزودن کلید ترجمه',
  'admin.translations.keyPlaceholder': 'unique.key.example',
  'admin.translations.valueLabel': 'مقدار',
  'admin.translations.cancel': 'انصراف',
  'admin.translations.add': 'افزودن کلید',
  'admin.translations.keyRequired': 'کلید الزامی است',
  'admin.translations.keyExists': 'کلید از قبل وجود دارد',
  'admin.translations.saved': 'ترجمه‌ها ذخیره شد',
  'admin.translations.nothingToSave': 'چیزی برای ذخیره نیست',
  'admin.saving': 'در حال ذخیره…',
    
  // Admin Booking Flow Config
  'admin.bookingFlow.title': 'پیکربندی جریان رزرو',
  'admin.bookingFlow.subtitle': 'کنترل زمان‌های در دسترس، تاریخ‌های بسته و توضیحات رزرو',
  'admin.bookingFlow.availableSlots': 'زمان‌های در دسترس',
  'admin.bookingFlow.availableSlotsHint': 'زمان‌ها را با کاما یا خط جدید و در فرمت ۲۴ ساعته وارد کنید؛ مثلا 09:00، 10:00، 11:30',
  'admin.bookingFlow.defaultDuration': 'مدت پیش‌فرض (دقیقه)',
  'admin.bookingFlow.buffer': 'فاصله (دقیقه)',
  'admin.bookingFlow.blackoutDates': 'تاریخ‌های بسته',
  'admin.bookingFlow.blackoutDatesHint': 'تاریخ‌ها به صورت YYYY-MM-DD با کاما یا خط جدید',
  'admin.bookingFlow.disclaimer': 'توضیحات رزرو',
  'admin.bookingFlow.saved': 'پیکربندی رزرو ذخیره شد',
  'admin.bookingFlow.saveFailed': 'ذخیره ناموفق بود',
  'admin.bookingFlow.loadFailed': 'بارگذاری پیکربندی ناموفق بود',
  'admin.saveGeneric': 'ذخیره',
  'admin.reloadGeneric': 'بارگذاری مجدد',
    // Videos page
    'videos.title': 'گالری ویدیو',
    'videos.subtitle': 'مشاهده روندهای واقعی، نظرات بیماران و راهنمایی‌های تخصصی',
    'videos.all': 'همه ویدیوها',
    'videos.searchPlaceholder': 'جستجوی ویدیو...',
    'videos.noResults': 'ویدیویی مطابق با معیارهای شما پیدا نشد',
    'videos.uncategorized': 'بدون دسته‌بندی',
    'videos.playerLabel': 'پخش‌کننده ویدیو',
    'videos.heroDescription': 'ویدیوهای ثبت‌شده در کلینیک که به‌صورت محلی میزبانی و بهینه شده‌اند.',
    'videos.heroPill': 'لحظه‌های منتخب کلینیک',
    'videos.heroStatVideosLabel': 'ویدیوی منتخب',
    'videos.heroStatMinutesLabel': 'دقایق روایت',
    'videos.heroStatMinutesValue': '{{minutes}} دقیقه',
    'videos.heroStatUpdatedLabel': 'به‌روزرسانی تازه',
    'videos.heroStatUpdatedValue': 'هفتگی',
    'videos.watch': 'مشاهده ویدیو',
    'videos.emptyStateTitle': 'ویدیوهای جدید در راهند',
    'videos.emptyStateBody': 'در حال آماده‌سازی ویدیوهای تازه از کلینیک هستیم. لطفاً به‌زودی دوباره سر بزنید یا ما را در اینستاگرام دنبال کنید.',
    'videos.typeVideo': 'ویدیو',
    'videos.typeImage': 'تصویر',
    'videos.typeCarousel': '{{count}} رسانه',
    'videos.capturedOn': 'ثبت شده در {{date}}',
    'videos.detailsTitle': 'جزئیات ویدیو',
    'videos.captionLabel': 'کپشن اینستاگرام',
    'videos.relatedMediaLabel': 'تصاویر گالری',
    'videos.sourceLink': 'مشاهده پست اصلی',
    // Magazine page
    'magazine.title': 'مجله زیبایی',
    'magazine.subtitle': 'بینش‌های تخصصی، نکات و جدیدترین روندهای مراقبت از مو و زیبایی',
    'magazine.featured': 'ویژه',
    'magazine.latest': 'جدیدترین مقالات',
    'magazine.loadMore': 'بارگذاری مقالات بیشتر',
    'magazine.categories': 'دسته‌بندی‌ها',
    'magazine.trending': 'داغ‌ترین‌ها',
    'magazine.popularTags': 'برچسب‌های محبوب',
    'magazine.general': 'عمومی',
    'magazine.backToMagazine': 'بازگشت به مجله',
    'magazine.noContent': 'محتوایی برای این مقاله موجود نیست.',
    'common.share': 'اشتراک‌گذاری',
    // Contact page
    'contact.subtitle': 'برای پاسخگویی به سوالات شما و شروع مسیر زیبایی شما کنار شما هستیم',
    'contact.form.namePlaceholder': 'نام شما',
    'contact.form.subjectPlaceholder': 'چطور می‌توانیم کمک کنیم؟',
    'contact.form.messagePlaceholder': 'درباره درخواست خود بیشتر بگویید...',
    'contact.form.phoneRequired': 'لطفاً شماره تماس خود را وارد کنید',
    'contact.map.title': 'نقشه تعاملی',
    'contact.map.addressPlaceholder': 'آدرس کلینیک شما',
    'contact.social.subtitle': 'برای دریافت نکات زیبایی، اخبار و پیشنهادهای ویژه همراه ما باشید',
    'contact.quickActions.title': 'اقدامات سریع',
    'contact.quickActions.empty': 'اقدام سریعی تنظیم نشده است.',
    'contact.faqs.title': 'سؤالات پرتکرار',
    'contact.faqs.subtitle': 'پاسخ‌های سریع به پرسش‌های رایج',
    'contact.faqs.viewAll': 'مشاهده همه پرسش‌ها',
    // Booking page
    'booking.subtitle': 'رزرو مشاوره یا خدمات تنها در چند گام ساده',
    'booking.selectDateTimeTitle': 'انتخاب تاریخ و زمان',
    'booking.chooseDate': 'انتخاب تاریخ',
    'booking.chooseTime': 'انتخاب زمان',
    'booking.noSlots': 'برای این تاریخ زمان خالی موجود نیست',
    'booking.selectDateFirst': 'ابتدا یک تاریخ انتخاب کنید',
    'booking.loadingTimes': 'در حال بارگذاری زمان‌ها...',
    'booking.yourInformation': 'اطلاعات شما',
    'booking.fullNamePlaceholder': 'نام و نام خانوادگی',
    'booking.additionalNotes': 'توضیحات تکمیلی',
    'booking.additionalNotesPlaceholder': 'درخواست خاص یا اطلاعات بیشتر...',
    'booking.bookingSummary': 'خلاصه رزرو',
    'booking.note': 'یادداشت',
    'booking.confirmedTitle': 'رزرو تایید شد!',
    'booking.confirmedBody': 'از انتخاب شما سپاسگزاریم. ایمیل تایید شامل جزئیات قرار برای شما ارسال شد.',
    'booking.yourAppointment': 'قرار شما',
    'booking.confirmationNumber': 'شماره تایید',
    'booking.bookAnother': 'رزرو جدید',
    'booking.downloadReceipt': 'دانلود رسید',
    'booking.back': 'بازگشت',
    'booking.continue': 'ادامه',
    // Brand & footer
    'brand.tagline': 'همراه مطمئن شما برای زیبایی طبیعی',
    'footer.linksGroupDefault': 'لینک‌ها',
    'brand.name': 'کاشت زیبایی',
    // Alts & labels
    'hero.homeAlt': 'تصویر درمان زیبایی',
    'about.missionHeroAlt': 'کلینیک و امکانات ما',
    'about.missionSecondaryAlt': 'فرآیند درمان ما',
    'testimonials.verifiedClient': 'مراجع تاییدشده',
    // Common
    'common.loading': 'در حال بارگذاری…',
    'about.noStats': 'آماری در دسترس نیست',
  // Chat widget
  'chat.title': 'گفتگو با ما',
  'chat.subtitle': 'آنلاین هستیم',
  'chat.placeholder': 'پیام خود را تایپ کنید...',
  'chat.greeting': 'سلام! چطور می‌تونیم کمکتون کنیم؟',
  'chat.autoReply': 'متشکریم! همکاران ما به‌زودی با شما تماس خواهند گرفت.',
  'chat.open': 'باز کردن چت',
  'chat.close': 'بستن چت',
  'chat.send': 'ارسال',
    // Admin common
    'admin.dashboard': 'داشبورد',
    'admin.bookings': 'رزروها',
    'admin.clients': 'مشتریان',
    'admin.services': 'خدمات',
    'admin.testimonials': 'نظرات',
    'admin.homeContent': 'محتوای خانه',
    'admin.aboutContent': 'محتوای درباره',
    'admin.contactContent': 'محتوای تماس',
    'admin.seoSettings': 'تنظیمات سئو',
    'admin.bookingConfig': 'پیکربندی رزرو',
    'admin.bookingInfo': 'کارت‌های اطلاعات رزرو',
  'admin.bookingInfo.addCard': 'افزودن کارت',
  'admin.bookingInfo.reload': 'بارگذاری مجدد',
  'admin.bookingInfo.iconLabel': 'آیکن (نام lucide)',
  'admin.bookingInfo.titleLabel': 'عنوان',
  'admin.bookingInfo.descriptionLabel': 'توضیحات',
  'admin.bookingInfo.orderLabel': 'ترتیب',
  'admin.bookingInfo.up': 'بالا',
  'admin.bookingInfo.down': 'پایین',
  'admin.bookingInfo.saved': 'ذخیره شد',
  'admin.bookingInfo.saveFailed': 'ذخیره ناموفق بود',
  'admin.bookingInfo.createFailed': 'ایجاد ناموفق بود',
  'admin.bookingInfo.deleteFailed': 'حذف ناموفق بود',
  'admin.bookingInfo.orderUpdated': 'ترتیب بروزرسانی شد',
  'admin.bookingInfo.reorderFailed': 'تغییر ترتیب ناموفق بود',
    'admin.newsletter': 'خبرنامه',
    'admin.translations': 'ترجمه‌ها',
    'admin.media': 'کتابخانه رسانه',
    'admin.videos': 'ویدیوها',
    'admin.magazine': 'مجله',
    'admin.messages': 'پیام‌ها',
    'admin.team': 'تیم',
    'admin.navigation': 'ناوبری',
    'admin.footerLinks': 'لینک‌های فوتر',
    'admin.settings': 'تنظیمات',
    'admin.accessControl': 'کنترل دسترسی',
    'admin.logout': 'خروج',
    'admin.profileSettings': 'تنظیمات پروفایل',
      // duplicate fa keys removed: email, phone, notes
    'admin.preferences': 'ترجیحات',
    'admin.searchPlaceholder': 'جستجو...',
    'admin.notifications': 'اعلان‌ها',
    'admin.exitAdmin': 'خروج از حالت مدیریت',
    'admin.enterAdmin': 'ورود به مدیریت',
    'admin.toggleToPublic': 'نمایش وب‌سایت',
    'admin.toggleToAdmin': 'پنل مدیریت',
    'admin.delete': 'حذف',
    'admin.edit': 'ویرایش',
    'admin.add': 'افزودن',
    'admin.loading': 'در حال بارگذاری…',
    'admin.noData': 'داده‌ای موجود نیست',
    'admin.panel': 'پنل مدیریت',
    'admin.viewProfile': 'مشاهده پروفایل',
  'admin.sendEmail': 'ارسال ایمیل',
  'admin.bookAppointment': 'رزرو قرار',
    'admin.clientsManagement': 'مدیریت مشتریان',
    'admin.clientsManagementSubtitle': 'مدیریت تمام اطلاعات و سوابق مشتری',
    'admin.addClient': 'افزودن مشتری',
    'admin.totalClients': 'کل مشتریان',
    'admin.active': 'فعال',
    'admin.inactive': 'غیرفعال',
    'admin.newThisMonth': 'جدید در این ماه',
    'admin.searchClientsPlaceholder': 'جستجو بر اساس نام، ایمیل یا شناسه...',
    'admin.allClients': 'همه مشتریان',
    'admin.export': 'خروجی',
    'admin.client': 'مشتری',
    'admin.contact': 'تماس',
    'admin.joinDate': 'تاریخ عضویت',
    'admin.lastVisit': 'آخرین مراجعه',
    'admin.status': 'وضعیت',
    'admin.actions': 'اقدامات',
    'admin.editClient': 'ویرایش مشتری',
    'admin.fullName': 'نام کامل',
    'admin.email': 'ایمیل',
    'admin.phone': 'تلفن',
    'admin.notes': 'یادداشت‌ها',
  // duplicate removed: admin.cancel
    'admin.saveChanges': 'ذخیره تغییرات',
    'admin.createClient': 'ایجاد مشتری',
    'admin.inactiveDash': '—',
    'admin.nameRequired': 'نام الزامی است',
    'admin.clientUpdated': 'مشتری بروزرسانی شد',
    'admin.clientAdded': 'مشتری اضافه شد',
    'admin.saveFailed': 'ذخیره ناموفق بود',
    'admin.deleteConfirm': 'حذف مشتری',
    'admin.clientDeleted': 'مشتری حذف شد',
    'admin.deleteFailed': 'حذف ناموفق بود',
    'admin.switchLanguage': 'تغییر زبان',
    'admin.dashboardOverview': 'نمای کلی داشبورد',
    'admin.dashboardWelcome': 'خوش آمدید! وضعیت امروز را مشاهده کنید.',
  'admin.totalRevenue': 'کل درآمد',
  'admin.totalBookings': 'کل رزروها',
  'admin.activeClients': 'مشتریان فعال',
  'admin.successRate': 'نرخ موفقیت',
    'admin.revenueOverview': 'نمای درآمد',
    'admin.servicesDistribution': 'توزیع خدمات',
    'admin.todaysSchedule': 'برنامه امروز',
    'admin.recentBookings': 'رزروهای اخیر',
    'admin.viewAll': 'مشاهده همه',
    'admin.quickActions': 'اقدامات سریع',
    'admin.newBooking': 'رزرو جدید',
    'admin.sendMessage': 'ارسال پیام',
    'admin.viewReports': 'مشاهده گزارش‌ها',
    'admin.priceRange': 'بازه قیمت',
  'admin.durationLabel': 'مدت زمان',
  'admin.start': 'شروع',
  'admin.end': 'پایان',
  'admin.required': 'ضروری',
    'admin.duration': 'مدت زمان',
    'admin.recovery': 'دوره نقاهت',
    'admin.servicesManagement': 'مدیریت خدمات',
    'admin.servicesManagementSubtitle': 'مدیریت تمام خدمات و روش‌ها',
    'admin.servicesContent': 'محتوای خدمات',
    'admin.servicesContentSubtitle': 'مدیریت خدمات و محتوای صفحه',
    'admin.servicesList': 'لیست خدمات',
    'admin.servicesHero': 'هیرو صفحه خدمات',
    'admin.servicesCta': 'بخش فراخوان (CTA) صفحه خدمات',
    'admin.ctaTitleEn': 'عنوان (English)',
    'admin.ctaTitleFa': 'عنوان (فارسی)',
    'admin.ctaBodyEn': 'متن (English)',
    'admin.ctaBodyFa': 'متن (فارسی)',
    'admin.ctaPrimaryEn': 'دکمه اصلی (English)',
    'admin.ctaPrimaryFa': 'دکمه اصلی (فارسی)',
    'admin.ctaSecondaryEn': 'دکمه ثانویه (English)',
    'admin.ctaSecondaryFa': 'دکمه ثانویه (فارسی)',
    'admin.heroTitleEn': 'عنوان (English)',
    'admin.heroTitleFa': 'عنوان (فارسی)',
    'admin.heroSubtitleEn': 'زیرعنوان (English)',
    'admin.heroSubtitleFa': 'زیرعنوان (فارسی)',
    'admin.saveHeroContent': 'ذخیره محتوای هیرو',
    'admin.heroContentSaved': 'محتوای هیرو با موفقیت ذخیره شد',
    'admin.heroContentSaveFailed': 'ذخیره محتوای هیرو ناموفق بود',
    'admin.addService': 'افزودن خدمت',
    'admin.totalServices': 'کل خدمات',
    'admin.withPriceRange': 'دارای بازه قیمت',
    'admin.withDuration': 'دارای مدت زمان',
    'admin.loadingServices': 'در حال بارگذاری خدمات…',
    'admin.serviceUpdated': 'خدمت بروزرسانی شد',
    'admin.serviceCreated': 'خدمت ایجاد شد',
    'admin.serviceDeleted': 'خدمت حذف شد',
    'admin.deleteServiceConfirm': 'حذف خدمت',
    'admin.slugConflict': 'اسلاگ از قبل وجود دارد',
    'admin.requiredFieldsMissing': 'فیلدهای لازم: عنوان، اسلاگ، توضیحات را پر کنید',
    'admin.editService': 'ویرایش خدمت',
    'admin.addNewService': 'افزودن خدمت جدید',
    'admin.serviceNameLabel': 'نام خدمت*',
    'admin.subtitleLabel': 'زیرعنوان',
    'admin.descriptionLabel': 'توضیحات*',
    'admin.slugLabel': 'اسلاگ*',
    'admin.startingPriceLabel': 'قیمت شروع*',
    'admin.recoveryTimeLabel': 'دوره نقاهت*',
    'admin.imageUrlLabel': 'آدرس تصویر',
    'admin.benefitsLabel': 'مزایا',
    'admin.processStepsLabel': 'مراحل فرآیند',
    'admin.stepTitleLabel': 'عنوان مرحله',
    'admin.faqLabel': 'سؤالات پرتکرار',
    'admin.benefitPlaceholder': 'متن مزیت',
    'admin.addBenefit': 'افزودن مزیت',
    'admin.remove': 'حذف',
    'admin.addStep': 'افزودن مرحله',
    'admin.questionPlaceholder': 'سؤال*',
    'admin.answerPlaceholder': 'پاسخ*',
    'admin.addFaq': 'افزودن سؤال',
    'admin.update': 'بروزرسانی',
    'admin.create': 'ایجاد',
    'admin.bookingsManagement': 'مدیریت رزروها',
    'admin.bookingsManagementSubtitle': 'مدیریت تمام قرارها و رزروها',
    'admin.newBookingAction': 'رزرو جدید',
    'admin.searchBookingsPlaceholder': 'جستجو بر اساس مشتری، شناسه یا خدمت...',
    'admin.allStatus': 'همه وضعیت‌ها',
    'admin.confirmed': 'تایید شده',
    'admin.pending': 'در انتظار',
    'admin.cancelled': 'لغو شده',
    'admin.completed': 'تکمیل شده',
    'admin.dateTime': 'تاریخ و زمان',
    'admin.price': 'قیمت',
    'admin.viewDetails': 'مشاهده جزئیات',
    'admin.confirm': 'تایید',
    'admin.close': 'بستن',
    'admin.editBooking': 'ویرایش رزرو',
    'admin.bookingDetails': 'جزئیات رزرو',
    'admin.clientName': 'نام مشتری',
    'admin.service': 'خدمت',
    'admin.date': 'تاریخ',
    'admin.time': 'زمان',
    'admin.clientRequired': 'مشتری و زمان شروع الزامی است',
    'admin.bookingUpdated': 'رزرو بروزرسانی شد',
    'admin.bookingCreated': 'رزرو ایجاد شد',
    'admin.deleteBookingConfirm': 'حذف این رزرو؟',
    'admin.deleted': 'حذف شد',
    'admin.editTestimonial': 'ویرایش نظر',
    'admin.addTestimonial': 'افزودن نظر',
    'admin.testimonialsManagement': 'نظرات',
    'admin.testimonialsSubtitle': 'مدیریت نظرات بیماران نمایش داده شده در صفحه اصلی',
    'admin.addTestimonialAction': 'افزودن نظر',
    'admin.name': 'نام',
    'admin.text': 'متن',
    'admin.ratingLabel': 'امتیاز (۱-۵)*',
    'admin.imageUrl': 'آدرس تصویر',
    'admin.nameTextRequired': 'نام و متن الزامی است',
    'admin.testimonialUpdated': 'نظر بروزرسانی شد',
    'admin.testimonialCreated': 'نظر ایجاد شد',
    'admin.deleteTestimonialConfirm': 'حذف نظر از',
  // Dashboard table & chart labels
  'admin.table.id': 'شناسه',
  'admin.table.client': 'مشتری',
  'admin.table.service': 'خدمت',
  'admin.table.status': 'وضعیت',
  'admin.month.jan': 'ژانویه',
  'admin.month.feb': 'فوریه',
  'admin.month.mar': 'مارس',
  'admin.month.apr': 'آوریل',
  'admin.month.may': 'مه',
  'admin.month.jun': 'ژوئن',
  'admin.status.inProgress': 'در حال انجام',
  'admin.status.upcoming': 'آتی',
  'admin.consultation': 'مشاوره',
  'admin.eyebrowDesign': 'طراحی ابرو',
    'admin.teamManagement': 'مدیریت تیم',
    'admin.teamManagementSubtitle': 'مدیریت پروفایل و وضعیت نمایش اعضای تیم',
    'admin.newMember': 'عضو جدید',
    'admin.totalMembers': 'کل اعضا',
    'admin.activeMembers': 'اعضای فعال',
    'admin.inactiveMembers': 'غیرفعال',
    'admin.visibilityPercent': 'درصد نمایش',
    'admin.deactivate': 'غیرفعال کردن',
    'admin.activate': 'فعال کردن',
    'admin.memberUpdated': 'عضو بروزرسانی شد',
    'admin.memberAdded': 'عضو اضافه شد',
    'admin.deleteMemberConfirm': 'حذف عضو تیم',
    'admin.statusUpdateFailed': 'بروزرسانی وضعیت ناموفق بود',
    'admin.editMember': 'ویرایش عضو',
    'admin.newMemberDialog': 'عضو جدید',
    'admin.role': 'نقش',
    'admin.bio': 'بیوگرافی',
    'admin.activeVisible': 'فعال / قابل نمایش',
    // Media Library
    'admin.mediaLibrary.title': 'کتابخانه رسانه',
    'admin.mediaLibrary.subtitle': 'مدیریت و مرور تصاویر و ویدیوهای آپلود شده',
    'admin.media.upload': 'آپلود',
    'admin.media.searchPlaceholder': 'جستجو بر اساس متن جایگزین، نام فایل یا لیبل‌ها',
    'admin.media.total': 'کل',
    'admin.media.filtered': 'فیلتر شده',
    'admin.media.noResults': 'رسانه‌ای مطابق جستجو یافت نشد.',
    'admin.media.loading': 'در حال بارگذاری رسانه…',
    'admin.media.uploadDialog': 'آپلود رسانه',
    'admin.media.altInput': 'متن جایگزین (برای تصاویر)',
    'admin.media.labelsPlaceholder': 'آرایه JSON لیبل‌ها مثلا ["hero","banner"]',
    'admin.media.uploading': 'در حال آپلود…',
    'admin.media.uploadImage': 'آپلود تصویر',
    'admin.media.selectFileError': 'فایل را انتخاب کنید',
    'admin.media.uploaded': 'آپلود شد',
    'admin.media.uploadFailed': 'آپلود ناموفق بود',
    'admin.media.chooseIcon': 'انتخاب آیکن',
    'admin.media.iconHelp': 'یک تصویر آپلود کنید یا از آیکن‌های Lucide انتخاب کنید',
    'admin.media.deleteConfirm': 'این مورد رسانه حذف شود؟',
    'admin.media.deleted': 'حذف شد',
    'admin.media.deleteFailed': 'حذف ناموفق بود',
    // Videos Management (Local Instagram import)
    'admin.videos.totalSuffix': 'ویدیو',
    'admin.videos.urlLabel': 'آدرس اینستاگرام',
    'admin.videos.urlPlaceholder': 'https://www.instagram.com/reel/XXXXXXXX/',
    'admin.videos.statusLabel': 'وضعیت اولیه',
    'admin.videos.importing': 'در حال واردسازی…',
    'admin.videos.clear': 'پاک کردن',
    'admin.videos.urlMissing': 'لطفاً لینک اینستاگرام را وارد کنید',
    'admin.videos.importSuccess': 'ویدیو با موفقیت وارد شد',
    'admin.videos.libraryEmpty': 'هنوز ویدیویی وارد نشده است.',
    'admin.videos.libraryEmptyCta': 'از فرم بالا برای وارد کردن اولین ریل استفاده کنید.',
    'admin.videos.deleteConfirm': 'ویدیو «{{title}}» حذف شود؟',
    'admin.videos.deleteSuccess': 'ویدیو حذف شد',
    'admin.videos.updateSuccess': 'ویدیو به‌روزرسانی شد',
    // Messages Management
    'admin.messagesManagement.title': 'پیام‌ها و درخواست‌ها',
    'admin.messagesManagement.subtitle': 'مدیریت همه پیام‌ها و درخواست‌های تماس مشتریان',
    'admin.messages.total': 'کل پیام‌ها',
    'admin.messages.new': 'جدید',
    'admin.messages.replied': 'پاسخ داده شده',
    'admin.messages.starred': 'ستاره‌دار',
    'admin.messages.inbox': 'صندوق ورودی',
    'admin.messages.selectPrompt': 'برای مشاهده جزئیات یک پیام را انتخاب کنید',
    'admin.messages.reply': 'پاسخ',
    'admin.messages.archive': 'بایگانی',
    'admin.messages.copyToClipboard': 'کپی در کلیپ‌بورد',
    'admin.messages.copied': 'در کلیپ‌بورد کپی شد',
    'admin.messages.copyFailed': 'کپی ناموفق بود',
    'admin.messages.markReplied': 'علامت به عنوان پاسخ داده شده',
    'admin.messages.markedReplied': 'به عنوان پاسخ داده شده علامت شد',
    'admin.messages.subjectPlaceholder': 'موضوع',
    'admin.messages.deleteConfirm': 'این پیام حذف شود؟',
    'admin.messages.deleteSuccess': 'پیام حذف شد',
    'admin.messages.deleteFailed': 'حذف ناموفق بود',
    'admin.messages.loadFailed': 'بارگذاری پیام‌ها ناموفق بود',
    'admin.messages.updateFailed': 'بروزرسانی ناموفق بود',
    'admin.messages.starredToast': 'ستاره‌دار شد',
    'admin.messages.unstarredToast': 'ستاره برداشته شد',
    'admin.messages.templateNote': 'این پنجره یک قالب پاسخ ارائه می‌دهد؛ ایمیل مستقیم ارسال نمی‌کند.',
    'admin.messages.template.line1': 'سلام',
    'admin.messages.template.line2': 'از تماس شما با کلینیک آوا بیوتی سپاسگزاریم. پیام شما دریافت شد و تیم ما به زودی پاسخ خواهد داد.',
    'admin.messages.template.summaryHeading': 'خلاصه درخواست شما:',
    'admin.messages.template.line3': 'اگر نیاز به کمک فوری دارید با شماره‌های موجود در صفحه تماس، تماس بگیرید.',
    'admin.messages.template.signature': 'با احترام،',
    'admin.messages.template.brand': 'کلینیک آوا بیوتی',
    // Newsletter Settings
    'admin.newsletterSettings.title': 'تنظیمات خبرنامه',
    'admin.newsletterSettings.subtitle': 'کنترل محتوای بخش خبرنامه در صفحه مجله و فوتر سایت.',
    'admin.newsletter.headlineLabel': 'عنوان*',
    'admin.newsletter.descriptionLabel': 'توضیحات',
    'admin.newsletter.buttonLabel': 'عنوان دکمه',
    'admin.newsletter.contentSection': 'محتوای خبرنامه',
    'admin.newsletter.headlinePlaceholder': 'همراه ما باشید',
    'admin.newsletter.descriptionPlaceholder': 'آخرین مقالات و نکات را در ایمیل دریافت کنید.',
    'admin.newsletter.buttonPlaceholder': 'اشتراک',
    'admin.newsletter.headlineRequired': 'عنوان الزامی است',
    'admin.newsletter.saved': 'تنظیمات خبرنامه ذخیره شد',
    'admin.newsletter.saveFailed': 'ذخیره ناموفق بود',
    'admin.newsletter.loadFailed': 'بارگذاری خبرنامه ناموفق بود',
    // SEO Settings
    'admin.seoSettings.title': 'تنظیمات سئو',
    'admin.seoSettings.subtitle': 'کنترل فیلدهای متای سئو جهانی مورد استفاده در سایت.',
    'admin.seo.globalSection': 'سئوی جهانی',
    'admin.seo.siteTitleLabel': 'عنوان سایت*',
    'admin.seo.metaDescriptionLabel': 'توضیحات متا',
    'admin.seo.ogImageLabel': 'آدرس تصویر OpenGraph',
    'admin.seo.siteTitlePlaceholder': 'کلینیک آوا بیوتی',
    'admin.seo.metaDescriptionPlaceholder': 'کلینیک تخصصی کاشت موی زنانه و ابرو...',
    'admin.seo.ogImagePlaceholder': 'https://.../og.jpg',
    'admin.seo.siteTitleRequired': 'عنوان سایت الزامی است',
    'admin.seo.saved': 'تنظیمات سئو ذخیره شد',
    'admin.seo.saveFailed': 'ذخیره ناموفق بود',
    'admin.seo.loadFailed': 'بارگذاری تنظیمات ناموفق بود',
  // Home Content Management
  'admin.homeContent.title': 'مدیریت محتوای خانه',
  'admin.homeContent.subtitle': 'ویرایش بخش‌های هیرو، آمار، ویژگی‌ها و فراخوان اقدام',
  'admin.homeContent.heroSection': 'هیرو',
  'admin.homeContent.statsSection': 'آمار',
  'admin.homeContent.addStat': 'افزودن آمار',
  'admin.homeContent.noStats': 'آماری تعریف نشده است.',
  'admin.homeContent.featuresSection': 'ویژگی‌ها',
  'admin.homeContent.addFeature': 'افزودن ویژگی',
  'admin.homeContent.noFeatures': 'ویژگی‌ای تعریف نشده است.',
  'admin.homeContent.ctaSection': 'بلوک فراخوان اقدام',
  'admin.homeContent.heroTitleLabel': 'عنوان',
  'admin.homeContent.heroSubtitleLabel': 'زیرعنوان',
  'admin.homeContent.heroDescriptionLabel': 'توضیحات',
  'admin.homeContent.heroImageLabel': 'تصویر هیرو',
  'admin.homeContent.heroImageUploadHint': 'یک تصویر JPG یا PNG با کیفیت بالا (حداقل عرض ۱۶۰۰ پیکسل) آپلود کنید.',
  'admin.homeContent.heroImageEmpty': 'هنوز تصویری انتخاب نشده است',
  'admin.homeContent.heroImageUpdated': 'تصویر هیرو به‌روزرسانی شد',
  'admin.homeContent.heroImageRemoved': 'تصویر هیرو حذف شد',
  'admin.homeContent.heroImageUpdateFailed': 'به‌روزرسانی تصویر هیرو ناموفق بود',
  'admin.homeContent.primaryCtaLabel': 'برچسب دکمه اصلی',
  'admin.homeContent.secondaryCtaLabel': 'برچسب دکمه ثانویه',
  'admin.homeContent.ctaHeadingLabel': 'سرعنوان',
  'admin.homeContent.ctaSubheadingLabel': 'زیرسرعنوان',
  'admin.homeContent.ctaButtonLabel': 'برچسب دکمه',
  'admin.homeContent.stat.editTitle': 'ویرایش آمار',
  'admin.homeContent.stat.addTitle': 'افزودن آمار',
  'admin.homeContent.stat.labelLabel': 'برچسب*',
  'admin.homeContent.stat.valueLabel': 'مقدار*',
  'admin.homeContent.stat.iconLabel': 'آیکن',
  'admin.homeContent.feature.editTitle': 'ویرایش ویژگی',
  'admin.homeContent.feature.addTitle': 'افزودن ویژگی',
  'admin.homeContent.feature.titleLabel': 'عنوان*',
  'admin.homeContent.feature.descriptionLabel': 'توضیحات',
  'admin.homeContent.feature.iconLabel': 'آیکن',
  'admin.homeContent.statRequired': 'برچسب و مقدار آمار الزامی است',
  'admin.homeContent.statValueNumber': 'مقدار باید عدد باشد',
  'admin.homeContent.featureTitleRequired': 'عنوان ویژگی الزامی است',
  'admin.homeContent.deleteStatConfirm': 'حذف آمار؟',
  'admin.homeContent.deleteFeatureConfirm': 'حذف ویژگی؟',
  'admin.homeContent.saved': 'محتوای خانه ذخیره شد',
  'admin.homeContent.saveFailed': 'ذخیره ناموفق بود',
  'admin.homeContent.loadFailed': 'بارگذاری محتوای خانه ناموفق بود',
  // About Content Management
  'admin.aboutContent.title': 'مدیریت محتوای درباره',
  'admin.aboutContent.subtitle': 'ویرایش خط زمان، ارزش‌ها، مهارت‌ها و ماموریت',
  'admin.aboutContent.timelineSection': 'خط زمان',
  'admin.aboutContent.addTimeline': 'افزودن آیتم خط زمان',
  'admin.aboutContent.noTimeline': 'آیتمی در خط زمان نیست.',
  'admin.aboutContent.valuesSection': 'ارزش‌ها',
  'admin.aboutContent.addValue': 'افزودن ارزش',
  'admin.aboutContent.noValues': 'هیچ ارزشی تعریف نشده.',
  'admin.aboutContent.skillsSection': 'مهارت‌ها',
  'admin.aboutContent.addSkill': 'افزودن مهارت',
  'admin.aboutContent.noSkills': 'هیچ مهارتی اضافه نشده.',
  'admin.aboutContent.missionSection': 'ماموریت',
  'admin.aboutContent.missionHelper': 'بیانیه کوتاه و نکات حمایتی',
  'admin.aboutContent.missionBullets': 'نکات ماموریت',
  'admin.aboutContent.addBullet': 'افزودن نکته',
  'admin.aboutContent.noBullets': 'هیچ نکته‌ای هنوز نیست.',
  'admin.aboutContent.timeline.editTitle': 'ویرایش خط زمان',
  'admin.aboutContent.timeline.addTitle': 'افزودن خط زمان',
  'admin.aboutContent.timeline.yearLabel': 'سال*',
  'admin.aboutContent.timeline.titleLabel': 'عنوان*',
  'admin.aboutContent.timeline.descriptionLabel': 'توضیحات',
  'admin.aboutContent.value.editTitle': 'ویرایش ارزش',
  'admin.aboutContent.value.addTitle': 'افزودن ارزش',
  'admin.aboutContent.value.titleLabel': 'عنوان*',
  'admin.aboutContent.value.descriptionLabel': 'توضیحات',
  'admin.aboutContent.value.iconLabel': 'آیکن',
  'admin.aboutContent.skill.editTitle': 'ویرایش مهارت',
  'admin.aboutContent.skill.addTitle': 'افزودن مهارت',
  'admin.aboutContent.skill.nameLabel': 'نام*',
  'admin.aboutContent.skill.levelLabel': 'سطح (۰-۱۰۰)*',
  'admin.aboutContent.bullet.editTitle': 'ویرایش نکته',
  'admin.aboutContent.bullet.addTitle': 'افزودن نکته',
  'admin.aboutContent.bullet.textLabel': 'متن*',
  'admin.aboutContent.timelineRequired': 'سال و عنوان الزامی است',
  'admin.aboutContent.timelineYearNumber': 'سال باید عدد باشد',
  'admin.aboutContent.valueTitleRequired': 'عنوان ارزش الزامی است',
  'admin.aboutContent.skillRequired': 'نام و سطح مهارت الزامی است',
  'admin.aboutContent.skillLevelRange': 'سطح باید بین ۰ تا ۱۰۰ باشد',
  'admin.aboutContent.bulletTextRequired': 'متن نکته الزامی است',
  'admin.aboutContent.deleteTimelineConfirm': 'حذف آیتم خط زمان؟',
  'admin.aboutContent.deleteValueConfirm': 'حذف ارزش؟',
  'admin.aboutContent.deleteSkillConfirm': 'حذف مهارت؟',
  'admin.aboutContent.deleteBulletConfirm': 'حذف نکته؟',
  'admin.aboutContent.saved': 'محتوای درباره ذخیره شد',
  'admin.aboutContent.saveFailed': 'ذخیره ناموفق بود',
  'admin.aboutContent.loadFailed': 'بارگذاری محتوای درباره ناموفق بود',
  // Contact Content Management
  'admin.contactContent.title': 'مدیریت محتوای تماس',
  'admin.contactContent.subtitle': 'ویرایش بلوک‌های اطلاعات، پرسش‌ها، شبکه‌های اجتماعی و اقدامات سریع',
  'admin.contactContent.blocksSection': 'بلوک‌های اطلاعات',
  'admin.contactContent.addBlock': 'افزودن بلوک',
  'admin.contactContent.noBlocks': 'بلوکی تعریف نشده است.',
  'admin.contactContent.faqSection': 'پرسش‌ها',
  'admin.contactContent.addFaq': 'افزودن پرسش',
  'admin.contactContent.noFaq': 'آیتم پرسشی نیست.',
  'admin.contactContent.socialSection': 'لینک‌های اجتماعی',
  'admin.contactContent.addSocial': 'افزودن لینک',
  'admin.contactContent.noSocial': 'لینک اجتماعی‌ای نیست.',
  'admin.contactContent.quickSection': 'اقدامات سریع',
  'admin.contactContent.addQuick': 'افزودن اقدام',
  'admin.contactContent.noQuick': 'اقدام سریعی نیست.',
  'admin.contactContent.mapSection': 'نقشه و موقعیت',
  'admin.contactContent.mapHint': 'مختصات را از گوگل مپس کپی کنید',
  'admin.contactContent.map.latitude': 'عرض جغرافیایی',
  'admin.contactContent.map.longitude': 'طول جغرافیایی',
  'admin.contactContent.map.zoom': 'بزرگنمایی',
  'admin.contactContent.map.markerLabel': 'برچسب نشانگر',
  'admin.contactContent.map.placeholder': 'برای نمایش نقشه زنده، مختصات را وارد کنید.',
  'admin.contactContent.block.editTitle': 'ویرایش بلوک',
  'admin.contactContent.block.addTitle': 'افزودن بلوک',
  'admin.contactContent.block.typeLabel': 'نوع*',
  'admin.contactContent.block.titleLabel': 'عنوان*',
  'admin.contactContent.block.valuesLabel': 'مقادیر*',
  'admin.contactContent.block.addValue': 'افزودن مقدار',
  'admin.contactContent.faq.editTitle': 'ویرایش پرسش',
  'admin.contactContent.faq.addTitle': 'افزودن پرسش',
  'admin.contactContent.faq.questionLabel': 'سؤال*',
  'admin.contactContent.faq.answerLabel': 'پاسخ*',
  'admin.contactContent.social.editTitle': 'ویرایش لینک اجتماعی',
  'admin.contactContent.social.addTitle': 'افزودن لینک اجتماعی',
  'admin.contactContent.social.platformLabel': 'پلتفرم*',
  'admin.contactContent.social.iconLabel': 'آیکن',
  'admin.contactContent.social.chooseIcon': 'انتخاب آیکن',
  'admin.contactContent.social.iconHint': 'یک تصویر آپلود کنید یا از آیکن‌های Lucide انتخاب کنید',
  'admin.contactContent.social.iconSourceLucide': 'آیکن Lucide',
  'admin.contactContent.social.iconSourceUpload': 'تصویر آپلودی',
  'admin.contactContent.social.iconSourceNone': 'پیش‌فرض',
  'admin.contactContent.social.urlLabel': 'آدرس*',
  'admin.contactContent.quick.editTitle': 'ویرایش اقدام سریع',
  'admin.contactContent.quick.addTitle': 'افزودن اقدام سریع',
  'admin.contactContent.quick.labelLabel': 'برچسب*',
  'admin.contactContent.quick.typeLabel': 'نوع*',
  'admin.contactContent.quick.targetLabel': 'هدف*',
  'admin.contactContent.blockTitleRequired': 'عنوان بلوک الزامی است',
  'admin.contactContent.blockValueRequired': 'حداقل یک مقدار الزامی است',
  'admin.contactContent.faqRequired': 'سؤال و پاسخ الزامی است',
  'admin.contactContent.socialRequired': 'پلتفرم و آدرس الزامی است',
  'admin.contactContent.quickRequired': 'برچسب و هدف الزامی است',
  'admin.contactContent.deleteBlockConfirm': 'حذف بلوک؟',
  'admin.contactContent.deleteFaqConfirm': 'حذف پرسش؟',
  'admin.contactContent.deleteSocialConfirm': 'حذف لینک اجتماعی؟',
  'admin.contactContent.deleteQuickConfirm': 'حذف اقدام سریع؟',
  'admin.contactContent.saved': 'محتوای تماس ذخیره شد',
  'admin.contactContent.saveFailed': 'ذخیره ناموفق بود',
  'admin.contactContent.loadFailed': 'بارگذاری محتوای تماس ناموفق بود',
  // Navigation Management
  'admin.navigationManagement.title': 'ناوبری',
  'admin.navigationManagement.addItem': 'افزودن آیتم',
  'admin.navigationManagement.saving': 'در حال ذخیره…',
  'admin.navigationManagement.save': 'ذخیره',
  'admin.navigationManagement.saved': 'ناوبری ذخیره شد',
  'admin.navigationManagement.loadFailed': 'بارگذاری ناوبری ناموفق بود',
  'admin.navigationManagement.saveFailed': 'ذخیره ناموفق بود',
  'admin.navigationManagement.label': 'برچسب',
  'admin.navigationManagement.path': 'مسیر',
  'admin.navigationManagement.visible': 'قابل نمایش',
  // Footer Links Management
  'admin.footerLinksManagement.title': 'لینک‌های فوتر',
  'admin.footerLinksManagement.addLink': 'افزودن لینک',
  'admin.footerLinksManagement.saving': 'در حال ذخیره…',
  'admin.footerLinksManagement.save': 'ذخیره',
  'admin.footerLinksManagement.saved': 'لینک‌های فوتر ذخیره شد',
  'admin.footerLinksManagement.loadFailed': 'بارگذاری لینک‌های فوتر ناموفق بود',
  'admin.footerLinksManagement.saveFailed': 'ذخیره ناموفق بود',
  'admin.footerLinksManagement.label': 'برچسب',
  'admin.footerLinksManagement.url': 'آدرس',
  'admin.footerLinksManagement.group': 'گروه',
    // Common additions
    'common.back': 'بازگشت',
    'common.continue': 'ادامه',
    'common.error': 'خطا',
    'common.failedToLoad': 'بارگذاری انجام نشد',
    'common.emDash': '—',
    'common.justNow': 'همین الان',
    // Home additions
    'home.loadFailed': 'بارگذاری محتوای صفحه اصلی ناموفق بود',
    // Services public additions
    'services.loadFailed': 'بارگذاری خدمات ناموفق بود',
    'services.loading': 'در حال بارگذاری خدمات…',
    'services.tabBenefits': 'مزایا',
    'services.tabProcess': 'فرایند',
    'services.tabFaq': 'سؤالات متداول',
    'services.benefitsSuffix': 'مزایای',
    'services.price': 'قیمت',
    'services.duration': 'مدت زمان',
    'services.recovery': 'دوره نقاهت',
    // Booking public additions
    'booking.selectServiceError': 'لطفاً خدمت، تاریخ و زمان را انتخاب کنید',
    'booking.submitSuccess': 'رزرو ارسال شد! به‌زودی تأیید می‌کنیم.',
    'booking.submitFailed': 'رزرو ناموفق بود',
    'booking.summary.service': 'خدمت:',
    'booking.summary.date': 'تاریخ:',
    'booking.summary.time': 'زمان:',
    'booking.summary.duration': 'مدت:',
    'booking.summary.price': 'قیمت:',
    // Contact public additions
    'contact.loadFailed': 'بارگذاری اطلاعات تماس ناموفق بود',
    'contact.loading': 'در حال بارگذاری…',
    'contact.form.subjectLabel': 'موضوع',
    'contact.form.emailPlaceholder': 'you@example.com',
    'contact.form.phonePlaceholder': '+98 (---) --- ----',
    'contact.form.sending': 'در حال ارسال…',
    'contact.form.sentSuccess': 'پیام ارسال شد! به‌زودی پاسخ می‌دهیم.',
    'contact.form.sentFailed': 'ارسال پیام ناموفق بود',
    'contact.faqs.moreQuestionsIntro': 'سوالات بیشتری دارید؟',
    // Magazine public additions
    'magazine.loadFailed': 'بارگذاری داده‌های مجله ناموفق بود',
    'magazine.loading': 'در حال بارگذاری…',
    'magazine.minReadSuffix': 'دقیقه مطالعه',
    'magazine.newsletter.defaultHeadline': 'عضویت در خبرنامه',
    'magazine.newsletter.defaultDescription': 'آخرین نکات زیبایی و پیشنهادهای اختصاصی را در صندوق ایمیل خود دریافت کنید',
    'magazine.newsletter.defaultButton': 'همین حالا عضو شوید',
    // Videos public additions
    'videos.loadFailed': 'بارگذاری ویدیوها ناموفق بود',
    'videos.loading': 'در حال بارگذاری ویدیوها…',
    'videos.viewsSuffix': 'بازدید',
    'videos.playerPlaceholder': 'پخش‌کننده ویدیو',
    'videos.instagram.statusHeading': 'وضعیت همگام‌سازی اینستاگرام',
    'videos.instagram.connected': 'متصل',
    'videos.instagram.disconnected': 'قطع',
    'videos.instagram.profile': 'پروفایل',
    'videos.instagram.notConnected': 'متصل نیست',
    'videos.instagram.lastSynced': 'آخرین همگام‌سازی',
    'videos.instagram.tokenExpiry': 'انقضای دسترسی',
    'videos.instagram.expiresInDays': 'انقضا تا {{days}} روز',
    'videos.instagram.feedSource': 'منبع فید',
    'videos.instagram.feedSourceUnknown': 'نامشخص',
    'videos.instagram.refreshFeed': 'به‌روزرسانی فید',
    'videos.instagram.openProfile': 'نمایش پروفایل اینستاگرام',
    'videos.instagram.aboutTitle': 'چطور کار می‌کند',
    'videos.instagram.aboutBody': 'ویدیوهای این صفحه مستقیماً از حساب رسمی اینستاگرام شما خوانده می‌شود تا جدیدترین نتایج دیده شود.',
    'videos.instagram.aboutItem1': 'فقط یکبار از پنل مدیریت احراز هویت کنید.',
    'videos.instagram.aboutItem2': 'فید به صورت خودکار همگام و برای سرعت بیشتر کش می‌شود.',
    'videos.instagram.aboutItem3': 'پست‌های جدید خیلی زود پس از انتشار در اینجا ظاهر می‌شوند.',
    'videos.instagram.adminHint': 'برای تعویض حساب، از پنل مدیریت ← محتوا ← ویدیوها اقدام کنید.',
    'videos.instagram.loginRequired': 'برای نمایش ریل‌ها و ویدیوها، لطفاً حساب اینستاگرام تجاری خود را از پنل مدیریت متصل کنید.',
    'videos.instagram.goToAdmin': 'ورود به پنل مدیریت',
    'videos.instagram.viewPost': 'مشاهده در اینستاگرام',
    'videos.instagram.typeVideo': 'ویدیو',
    'videos.instagram.typeImage': 'تصویر',
    'videos.instagram.minutesAgo': '{{minutes}} دقیقه پیش',
    'videos.instagram.hoursAgo': '{{hours}} ساعت پیش',
    'videos.instagram.daysAgo': '{{days}} روز پیش',
    // Admin Magazine Management
    'admin.magazine.totalSuffix': 'مجموع مقالات',
    'admin.magazine.newArticle': 'مقاله جدید',
    'admin.magazine.editArticle': 'ویرایش مقاله',
    'admin.magazine.titleRequired': 'عنوان و اسلاگ الزامی است',
    'admin.magazine.updated': 'مقاله بروزرسانی شد',
    'admin.magazine.created': 'مقاله ایجاد شد',
    'admin.magazine.slugConflict': 'اسلاگ از قبل وجود دارد',
    'admin.magazine.saveFailed': 'ذخیره ناموفق بود',
    'admin.magazine.loadFailed': 'بارگذاری محتوا ناموفق بود',
    'admin.magazine.featureToggleFailed': 'تغییر وضعیت ویژه ناموفق بود',
    'admin.magazine.deleteConfirm': 'حذف مقاله',
    'admin.magazine.deleteFailed': 'حذف ناموفق بود',
    'admin.magazine.featured': 'ویژه',
    'admin.magazine.unfeature': 'لغو ویژه',
    'admin.magazine.feature': 'ویژه کردن',
    'admin.magazine.slugLabel': 'اسلاگ*',
    'admin.magazine.titleLabel': 'عنوان*',
    'admin.magazine.excerptLabel': 'خلاصه',
    'admin.magazine.imageUrlLabel': 'آدرس تصویر',
    'admin.magazine.readTimeLabel': 'زمان مطالعه (دقیقه)',
    'admin.magazine.statusLabel': 'وضعیت',
    'admin.magazine.featuredLabel': 'ویژه',
    'admin.magazine.categoryLabel': 'دسته‌بندی',
    'admin.magazine.tagsLabel': 'برچسب‌ها',
    'admin.magazine.noTags': 'بدون برچسب',
    'admin.magazine.update': 'بروزرسانی',
    'admin.magazine.create': 'ایجاد',
    // Admin Users Management
    'admin.adminUsers.title': 'کنترل دسترسی',
    'admin.adminUsers.subtitle': 'مدیریت کاربران و نقش‌های ادمین',
    'admin.adminUsers.addUser': 'افزودن کاربر ادمین',
    'admin.adminUsers.total': 'کل',
    'admin.adminUsers.active': 'فعال',
    'admin.adminUsers.inactive': 'غیرفعال',
    'admin.adminUsers.superadmins': 'سوپر ادمین‌ها',
    'admin.adminUsers.searchPlaceholder': 'جستجوی ایمیل، نام، نقش...',
    'admin.adminUsers.allRoles': 'همه نقش‌ها',
    'admin.adminUsers.superadminPlural': 'سوپرادمین‌ها',
    'admin.adminUsers.adminPlural': 'ادمین‌ها',
    'admin.adminUsers.editorPlural': 'ویرایشگرها',
    'admin.adminUsers.viewerPlural': 'بیننده‌ها',
    'admin.adminUsers.emailOptional': 'ایمیل (اختیاری اگر نام کاربری باشد)',
    'admin.adminUsers.usernameOptional': 'نام کاربری (اختیاری اگر ایمیل باشد)',
    'admin.adminUsers.usernameLabel': 'نام کاربری',
    'admin.adminUsers.nameLabel': 'نام',
    'admin.adminUsers.roleLabel': 'نقش',
    'admin.adminUsers.statusLabel': 'وضعیت',
    'admin.adminUsers.initialPassword': 'گذرواژه اولیه',
    'admin.adminUsers.resetPasswordOptional': 'بازنشانی گذرواژه (اختیاری)',
    'admin.adminUsers.deactivate': 'غیرفعال کردن',
    'admin.adminUsers.activate': 'فعال کردن',
    'admin.adminUsers.viewDetails': 'جزئیات',
    'admin.adminUsers.edit': 'ویرایش',
    'admin.adminUsers.delete': 'حذف',
    'admin.adminUsers.detailsTitle': 'جزئیات کاربر ادمین',
    'admin.adminUsers.editTitle': 'ویرایش کاربر ادمین',
    'admin.adminUsers.addTitle': 'افزودن کاربر ادمین',
    'admin.adminUsers.emailOrUsernameRequired': 'ایمیل یا نام کاربری الزامی است',
    'admin.adminUsers.passwordRequired': 'گذرواژه الزامی است',
    'admin.adminUsers.updated': 'کاربر ادمین بروزرسانی شد',
    'admin.adminUsers.created': 'کاربر ادمین ایجاد شد',
    'admin.adminUsers.emailExists': 'ایمیل از قبل وجود دارد',
    'admin.adminUsers.saveFailed': 'ذخیره ناموفق بود',
    'admin.adminUsers.deleteConfirm': 'حذف کاربر ادمین',
    'admin.adminUsers.deleteFailed': 'حذف ناموفق بود',
    'admin.adminUsers.deleted': 'کاربر ادمین حذف شد',
    'admin.adminUsers.saveChanges': 'ذخیره تغییرات',
    'admin.adminUsers.createUser': 'ایجاد کاربر',
    // Messages Management remaining literals mapping
    'admin.messages.replyButton': 'پاسخ',
    'admin.messages.archiveButton': 'بایگانی',
    'admin.messages.replyTo': 'پاسخ به',
    'admin.messages.subjectLabel': 'موضوع',
    'admin.messages.copyToClipboardButton': 'کپی در کلیپ‌بورد',
    'admin.messages.markRepliedButton': 'علامت پاسخ داده شده',
  // duplicates removed (use existing starredToast/unstarredToast)
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children, storageKey = 'lang_public', defaultLanguage = 'fa' }: LanguageProviderProps) {
  const readStoredLanguage = () => {
    if (typeof window === 'undefined' || typeof window.localStorage === 'undefined') {
      return defaultLanguage;
    }
    try {
      const stored = window.localStorage.getItem(storageKey) || (storageKey !== 'lang' ? window.localStorage.getItem('lang') : null);
      if (stored === 'fa' || stored === 'en') return stored as Language;
    } catch {
      // ignore
    }
    return defaultLanguage;
  };

  const [language, setLanguage] = useState<Language>(readStoredLanguage);
  const [languages, setLanguages] = useState<Language[]>(['en', 'fa']);

  // Support query param override (?l=en|fa) on load; persist to localStorage.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const param = new URLSearchParams(window.location.search).get('l');
    if (param === 'en' || param === 'fa') {
      setLanguage(param);
      try { window.localStorage?.setItem(storageKey, param); } catch { /* ignore */ }
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const toggleLanguage = () => {
    setLanguage((prev) => {
      const idx = languages.indexOf(prev);
      const fallback = defaultLanguage || 'fa';
      const next = (languages[(idx + 1) % languages.length] || fallback) as Language;
      if (typeof window !== 'undefined') {
        try { window.localStorage?.setItem(storageKey, next); } catch { /* ignore */ }
      }
      return next;
    });
  };

  const t = (key: string, vars?: Record<string, string | number>): string => {
    // Use index access to avoid TypeScript narrowing issues with dynamic keys
    // This maintains safety while allowing any defined translation key.
    const dict: Record<string,string> = translations[language] as any;
    let template = dict[key] || key;
    if (!vars) return template;
    for (const [varKey, value] of Object.entries(vars)) {
      const pattern = new RegExp(`{{\s*${varKey}\s*}}`, 'g');
      template = template.replace(pattern, String(value));
    }
    return template;
  };

  const isRTL = language === 'fa';

  // Keep <html> element in sync with language and direction for accessibility and SEO
  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
      document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    }
  }, [language, isRTL]);

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-persian' : 'font-english'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
